/* ============================================================
   CONTENIDO de Japanese N1 Path
   Edita SOLO este archivo para anadir o corregir contenido.
   Estructura: window.CONTENT = { kanji:[...], vocab:[...], grammar:[...] }
   ============================================================ */
window.CONTENT = {

/* ---------------- KANJI (N5) ---------------- */
kanji: [
 {c:"木",kun:"き",on:"モク・ボク",say:"き",mean:"Árbol · madera",ej:"木曜日",ejr:"もくようび",ejt:"jueves",tip:"Un tronco vertical con dos ramas que caen.",lvl:"N5"},
 {c:"水",kun:"みず",on:"スイ",say:"みず",mean:"Agua",ej:"水曜日",ejr:"すいようび",ejt:"miércoles",tip:"Una corriente de agua fluyendo.",lvl:"N5"},
 {c:"火",kun:"ひ",on:"カ",say:"ひ",mean:"Fuego",ej:"火曜日",ejr:"かようび",ejt:"martes",tip:"Una figura con chispas saltando: fuego.",lvl:"N5"},
 {c:"山",kun:"やま",on:"サン",say:"やま",mean:"Montaña",ej:"富士山",ejr:"ふじさん",ejt:"monte Fuji",tip:"Tres picos: una montaña.",lvl:"N5"},
 {c:"川",kun:"かわ",on:"セン",say:"かわ",mean:"Río",ej:"川",ejr:"かわ",ejt:"río",tip:"Tres líneas de agua en paralelo.",lvl:"N5"},
 {c:"日",kun:"ひ",on:"ニチ・ジツ",say:"ひ",mean:"Sol · día",ej:"日本",ejr:"にほん",ejt:"Japón",tip:"El sol dentro de un marco.",lvl:"N5"},
 {c:"月",kun:"つき",on:"ゲツ・ガツ",say:"つき",mean:"Luna · mes",ej:"月曜日",ejr:"げつようび",ejt:"lunes",tip:"Una luna creciente.",lvl:"N5"},
 {c:"人",kun:"ひと",on:"ジン・ニン",say:"ひと",mean:"Persona",ej:"日本人",ejr:"にほんじん",ejt:"persona japonesa",tip:"Dos piernas caminando.",lvl:"N5"},
 {c:"大",kun:"おお",on:"ダイ・タイ",say:"おおきい",mean:"Grande",ej:"大学",ejr:"だいがく",ejt:"universidad",tip:"Una persona con los brazos abiertos: grande.",lvl:"N5"},
 {c:"小",kun:"ちい",on:"ショウ",say:"ちいさい",mean:"Pequeño",ej:"小さい",ejr:"ちいさい",ejt:"pequeño",tip:"Algo partido en trocitos diminutos.",lvl:"N5"},
 {c:"口",kun:"くち",on:"コウ",say:"くち",mean:"Boca",ej:"入口",ejr:"いりぐち",ejt:"entrada",tip:"Una boca abierta, cuadrada.",lvl:"N5"},
 {c:"目",kun:"め",on:"モク",say:"め",mean:"Ojo",ej:"目",ejr:"め",ejt:"ojo",tip:"Un ojo puesto de pie.",lvl:"N5"},
 {c:"一",kun:"ひと(つ)",on:"イチ・イツ",say:"いち",mean:"Uno",ej:"一つ",ejr:"ひとつ",ejt:"uno (objeto)",tip:"Una sola línea: el número uno.",lvl:"N5"},
 {c:"二",kun:"ふた(つ)",on:"ニ",say:"に",mean:"Dos",ej:"二つ",ejr:"ふたつ",ejt:"dos (objetos)",tip:"Dos líneas: el número dos.",lvl:"N5"},
 {c:"三",kun:"み(っつ)",on:"サン",say:"さん",mean:"Tres",ej:"三つ",ejr:"みっつ",ejt:"tres (objetos)",tip:"Tres líneas apiladas.",lvl:"N5"},
 {c:"四",kun:"よ(っつ)・よん",on:"シ",say:"よん",mean:"Cuatro",ej:"四つ",ejr:"よっつ",ejt:"cuatro (objetos)",tip:"Una boca con piernas: el cuatro.",lvl:"N5"},
 {c:"五",kun:"いつ(つ)",on:"ゴ",say:"ご",mean:"Cinco",ej:"五つ",ejr:"いつつ",ejt:"cinco (objetos)",tip:"Líneas cruzadas: el cinco.",lvl:"N5"},
 {c:"中",kun:"なか",on:"チュウ",say:"なか",mean:"Centro · dentro",ej:"中国",ejr:"ちゅうごく",ejt:"China",tip:"Una línea que atraviesa el centro de una caja.",lvl:"N5"},
 {c:"本",kun:"もと",on:"ホン",say:"ほん",mean:"Libro · origen",ej:"日本",ejr:"にほん",ejt:"Japón",tip:"Un árbol con una marca en la raíz: el origen.",lvl:"N5"},
 {c:"学",kun:"まな(ぶ)",on:"ガク",say:"がく",mean:"Aprender · estudio",ej:"学生",ejr:"がくせい",ejt:"estudiante",tip:"Un niño bajo un techo, aprendiendo.",lvl:"N5"},
 {c:"生",kun:"い(きる)・なま",on:"セイ・ショウ",say:"せい",mean:"Vida · nacer",ej:"先生",ejr:"せんせい",ejt:"profesor",tip:"Un brote que nace de la tierra.",lvl:"N5"},
 {c:"先",kun:"さき",on:"セン",say:"せん",mean:"Antes · anterior",ej:"先生",ejr:"せんせい",ejt:"profesor",tip:"Una persona que va por delante.",lvl:"N5"},
 {c:"年",kun:"とし",on:"ネン",say:"とし",mean:"Año",ej:"今年",ejr:"ことし",ejt:"este año",tip:"El paso de las cosechas: un año.",lvl:"N5"},
 {c:"円",kun:"まる(い)",on:"エン",say:"えん",mean:"Yen · redondo",ej:"百円",ejr:"ひゃくえん",ejt:"cien yenes",tip:"Una moneda redonda: el yen.",lvl:"N5"},
 {c:"六",kun:"む(つ)",on:"ロク",say:"ろく",mean:"Seis",ej:"六時",ejr:"ろくじ",ejt:"las seis",lvl:"N5"},
 {c:"七",kun:"なな(つ)",on:"シチ",say:"なな",mean:"Siete",ej:"七時",ejr:"しちじ",ejt:"las siete",lvl:"N5"},
 {c:"八",kun:"や(つ)",on:"ハチ",say:"はち",mean:"Ocho",ej:"八時",ejr:"はちじ",ejt:"las ocho",lvl:"N5"},
 {c:"九",kun:"ここの(つ)",on:"キュウ・ク",say:"きゅう",mean:"Nueve",ej:"九時",ejr:"くじ",ejt:"las nueve",lvl:"N5"},
 {c:"十",kun:"とお",on:"ジュウ",say:"じゅう",mean:"Diez",ej:"十円",ejr:"じゅうえん",ejt:"diez yenes",lvl:"N5"},
 {c:"百",on:"ヒャク",say:"ひゃく",mean:"Cien",ej:"百円",ejr:"ひゃくえん",ejt:"cien yenes",lvl:"N5"},
 {c:"千",kun:"ち",on:"セン",say:"せん",mean:"Mil",ej:"千円",ejr:"せんえん",ejt:"mil yenes",lvl:"N5"},
 {c:"万",on:"マン・バン",say:"まん",mean:"Diez mil",ej:"一万",ejr:"いちまん",ejt:"diez mil",lvl:"N5"},
 {c:"金",kun:"かね",on:"キン・コン",say:"かね",mean:"Oro · dinero",ej:"金曜日",ejr:"きんようび",ejt:"viernes",lvl:"N5"},
 {c:"土",kun:"つち",on:"ド・ト",say:"つち",mean:"Tierra",ej:"土曜日",ejr:"どようび",ejt:"sábado",lvl:"N5"},
 {c:"時",kun:"とき",on:"ジ",say:"とき",mean:"Tiempo · hora",ej:"時間",ejr:"じかん",ejt:"tiempo, hora",lvl:"N5"},
 {c:"分",kun:"わ(ける)",on:"フン・ブン",say:"ふん",mean:"Minuto · dividir",ej:"五分",ejr:"ごふん",ejt:"cinco minutos",lvl:"N5"},
 {c:"半",kun:"なか(ば)",on:"ハン",say:"はん",mean:"Mitad",ej:"半分",ejr:"はんぶん",ejt:"la mitad",lvl:"N5"},
 {c:"今",kun:"いま",on:"コン・キン",say:"いま",mean:"Ahora",ej:"今",ejr:"いま",ejt:"ahora",lvl:"N5"},
 {c:"週",on:"シュウ",say:"しゅう",mean:"Semana",ej:"来週",ejr:"らいしゅう",ejt:"la próxima semana",lvl:"N5"},
 {c:"曜",on:"ヨウ",say:"よう",mean:"Día de la semana",ej:"曜日",ejr:"ようび",ejt:"día de la semana",lvl:"N5"},
 {c:"毎",on:"マイ",say:"まい",mean:"Cada",ej:"毎日",ejr:"まいにち",ejt:"cada día",lvl:"N5"},
 {c:"午",on:"ゴ",say:"ご",mean:"Mediodía",ej:"午後",ejr:"ごご",ejt:"por la tarde",lvl:"N5"},
 {c:"前",kun:"まえ",on:"ゼン",say:"まえ",mean:"Antes · delante",ej:"前",ejr:"まえ",ejt:"antes, delante",lvl:"N5"},
 {c:"後",kun:"うし(ろ)・あと",on:"ゴ・コウ",say:"あと",mean:"Después · detrás",ej:"後ろ",ejr:"うしろ",ejt:"detrás",lvl:"N5"},
 {c:"何",kun:"なに・なん",on:"カ",say:"なに",mean:"Qué",ej:"何",ejr:"なに",ejt:"qué",lvl:"N5"},
 {c:"男",kun:"おとこ",on:"ダン・ナン",say:"おとこ",mean:"Hombre",ej:"男の人",ejr:"おとこのひと",ejt:"hombre",lvl:"N5"},
 {c:"女",kun:"おんな",on:"ジョ・ニョ",say:"おんな",mean:"Mujer",ej:"女の人",ejr:"おんなのひと",ejt:"mujer",lvl:"N5"},
 {c:"子",kun:"こ",on:"シ・ス",say:"こ",mean:"Niño · hijo",ej:"子ども",ejr:"こども",ejt:"niño",lvl:"N5"},
 {c:"父",kun:"ちち",on:"フ",say:"ちち",mean:"Padre",ej:"父",ejr:"ちち",ejt:"(mi) padre",lvl:"N5"},
 {c:"母",kun:"はは",on:"ボ",say:"はは",mean:"Madre",ej:"母",ejr:"はは",ejt:"(mi) madre",lvl:"N5"},
 {c:"友",kun:"とも",on:"ユウ",say:"とも",mean:"Amigo",ej:"友だち",ejr:"ともだち",ejt:"amigo",lvl:"N5"},
 {c:"名",kun:"な",on:"メイ・ミョウ",say:"な",mean:"Nombre",ej:"名前",ejr:"なまえ",ejt:"nombre",lvl:"N5"},
 {c:"手",kun:"て",on:"シュ",say:"て",mean:"Mano",ej:"手",ejr:"て",ejt:"mano",lvl:"N5"},
 {c:"足",kun:"あし",on:"ソク",say:"あし",mean:"Pie · pierna",ej:"足",ejr:"あし",ejt:"pie, pierna",lvl:"N5"},
 {c:"上",kun:"うえ・あ(げる)",on:"ジョウ",say:"うえ",mean:"Arriba · encima",ej:"上",ejr:"うえ",ejt:"arriba",lvl:"N5"},
 {c:"下",kun:"した・さ(げる)",on:"カ・ゲ",say:"した",mean:"Abajo · debajo",ej:"下",ejr:"した",ejt:"abajo",lvl:"N5"},
 {c:"左",kun:"ひだり",on:"サ",say:"ひだり",mean:"Izquierda",ej:"左",ejr:"ひだり",ejt:"izquierda",lvl:"N5"},
 {c:"右",kun:"みぎ",on:"ウ・ユウ",say:"みぎ",mean:"Derecha",ej:"右",ejr:"みぎ",ejt:"derecha",lvl:"N5"},
 {c:"外",kun:"そと・ほか",on:"ガイ・ゲ",say:"そと",mean:"Fuera · exterior",ej:"外",ejr:"そと",ejt:"fuera",lvl:"N5"},
 {c:"東",kun:"ひがし",on:"トウ",say:"ひがし",mean:"Este (dirección)",ej:"東京",ejr:"とうきょう",ejt:"Tokio",lvl:"N5"},
 {c:"西",kun:"にし",on:"セイ・サイ",say:"にし",mean:"Oeste",ej:"西",ejr:"にし",ejt:"oeste",lvl:"N5"},
 {c:"南",kun:"みなみ",on:"ナン",say:"みなみ",mean:"Sur",ej:"南",ejr:"みなみ",ejt:"sur",lvl:"N5"},
 {c:"北",kun:"きた",on:"ホク",say:"きた",mean:"Norte",ej:"北",ejr:"きた",ejt:"norte",lvl:"N5"},
 {c:"天",kun:"あめ・あま",on:"テン",say:"てん",mean:"Cielo",ej:"天気",ejr:"てんき",ejt:"tiempo (clima)",lvl:"N5"},
 {c:"空",kun:"そら・あ(く)",on:"クウ",say:"そら",mean:"Cielo · vacío",ej:"空",ejr:"そら",ejt:"cielo",lvl:"N5"},
 {c:"気",on:"キ・ケ",say:"き",mean:"Energía · ánimo",ej:"元気",ejr:"げんき",ejt:"energía, salud",lvl:"N5"},
 {c:"雨",kun:"あめ",on:"ウ",say:"あめ",mean:"Lluvia",ej:"雨",ejr:"あめ",ejt:"lluvia",lvl:"N5"},
 {c:"高",kun:"たか(い)",on:"コウ",say:"たかい",mean:"Alto · caro",ej:"高い",ejr:"たかい",ejt:"alto, caro",lvl:"N5"},
 {c:"安",kun:"やす(い)",on:"アン",say:"やすい",mean:"Barato · tranquilo",ej:"安い",ejr:"やすい",ejt:"barato",lvl:"N5"},
 {c:"新",kun:"あたら(しい)",on:"シン",say:"あたらしい",mean:"Nuevo",ej:"新しい",ejr:"あたらしい",ejt:"nuevo",lvl:"N5"},
 {c:"古",kun:"ふる(い)",on:"コ",say:"ふるい",mean:"Viejo · usado",ej:"古い",ejr:"ふるい",ejt:"viejo",lvl:"N5"},
 {c:"多",kun:"おお(い)",on:"タ",say:"おおい",mean:"Mucho · numeroso",ej:"多い",ejr:"おおい",ejt:"mucho, numeroso",lvl:"N5"},
 {c:"少",kun:"すく(ない)・すこ(し)",on:"ショウ",say:"すこし",mean:"Poco",ej:"少し",ejr:"すこし",ejt:"un poco",lvl:"N5"},
 {c:"長",kun:"なが(い)",on:"チョウ",say:"ながい",mean:"Largo · jefe",ej:"長い",ejr:"ながい",ejt:"largo",lvl:"N5"},
 {c:"白",kun:"しろ(い)",on:"ハク・ビャク",say:"しろい",mean:"Blanco",ej:"白い",ejr:"しろい",ejt:"blanco",lvl:"N5"},
 {c:"校",on:"コウ",say:"こう",mean:"Escuela",ej:"学校",ejr:"がっこう",ejt:"escuela",lvl:"N5"},
 {c:"語",kun:"かた(る)",on:"ゴ",say:"ご",mean:"Idioma · palabra",ej:"日本語",ejr:"にほんご",ejt:"japonés (idioma)",lvl:"N5"},
 {c:"国",kun:"くに",on:"コク",say:"くに",mean:"País",ej:"国",ejr:"くに",ejt:"país",lvl:"N5"},
 {c:"駅",on:"エキ",say:"えき",mean:"Estación",ej:"駅",ejr:"えき",ejt:"estación de tren",lvl:"N5"},
 {c:"店",kun:"みせ",on:"テン",say:"みせ",mean:"Tienda",ej:"店",ejr:"みせ",ejt:"tienda",lvl:"N5"},
 {c:"社",kun:"やしろ",on:"シャ",say:"しゃ",mean:"Empresa · santuario",ej:"会社",ejr:"かいしゃ",ejt:"empresa",lvl:"N5"},
 {c:"会",kun:"あ(う)",on:"カイ・エ",say:"あう",mean:"Reunirse · encontrar",ej:"会う",ejr:"あう",ejt:"encontrarse con",lvl:"N5"},
 {c:"車",kun:"くるま",on:"シャ",say:"くるま",mean:"Coche · vehículo",ej:"車",ejr:"くるま",ejt:"coche",lvl:"N5"},
 {c:"電",on:"デン",say:"でん",mean:"Electricidad",ej:"電車",ejr:"でんしゃ",ejt:"tren",lvl:"N5"},
 {c:"道",kun:"みち",on:"ドウ",say:"みち",mean:"Camino · calle",ej:"道",ejr:"みち",ejt:"camino, calle",lvl:"N5"},
 {c:"行",kun:"い(く)・おこな(う)",on:"コウ・ギョウ",say:"いく",mean:"Ir",ej:"行く",ejr:"いく",ejt:"ir",lvl:"N5"},
 {c:"来",kun:"く(る)",on:"ライ",say:"くる",mean:"Venir",ej:"来る",ejr:"くる",ejt:"venir",lvl:"N5"},
 {c:"見",kun:"み(る)",on:"ケン",say:"みる",mean:"Ver · mirar",ej:"見る",ejr:"みる",ejt:"ver",lvl:"N5"},
 {c:"聞",kun:"き(く)",on:"ブン・モン",say:"きく",mean:"Escuchar · preguntar",ej:"聞く",ejr:"きく",ejt:"escuchar",lvl:"N5"},
 {c:"食",kun:"た(べる)",on:"ショク",say:"たべる",mean:"Comer",ej:"食べる",ejr:"たべる",ejt:"comer",lvl:"N5"},
 {c:"飲",kun:"の(む)",on:"イン",say:"のむ",mean:"Beber",ej:"飲む",ejr:"のむ",ejt:"beber",lvl:"N5"},
 {c:"読",kun:"よ(む)",on:"ドク",say:"よむ",mean:"Leer",ej:"読む",ejr:"よむ",ejt:"leer",lvl:"N5"},
 {c:"書",kun:"か(く)",on:"ショ",say:"かく",mean:"Escribir",ej:"書く",ejr:"かく",ejt:"escribir",lvl:"N5"},
 {c:"話",kun:"はな(す)・はなし",on:"ワ",say:"はなす",mean:"Hablar · historia",ej:"話す",ejr:"はなす",ejt:"hablar",lvl:"N5"},
 {c:"買",kun:"か(う)",on:"バイ",say:"かう",mean:"Comprar",ej:"買う",ejr:"かう",ejt:"comprar",lvl:"N5"},
 {c:"出",kun:"で(る)・だ(す)",on:"シュツ",say:"でる",mean:"Salir · sacar",ej:"出る",ejr:"でる",ejt:"salir",lvl:"N5"},
 {c:"入",kun:"はい(る)・い(れる)",on:"ニュウ",say:"はいる",mean:"Entrar · meter",ej:"入る",ejr:"はいる",ejt:"entrar",lvl:"N5"},
 {c:"立",kun:"た(つ)",on:"リツ",say:"たつ",mean:"Estar de pie",ej:"立つ",ejr:"たつ",ejt:"ponerse de pie",lvl:"N5"},
 {c:"休",kun:"やす(む)",on:"キュウ",say:"やすむ",mean:"Descansar",ej:"休む",ejr:"やすむ",ejt:"descansar",lvl:"N5"},
 {c:"言",kun:"い(う)・こと",on:"ゲン・ゴン",say:"いう",mean:"Decir · palabra",ej:"言う",ejr:"いう",ejt:"decir",lvl:"N5"}
],

/* ---------------- VOCABULARIO (N5) ---------------- */
vocab: [
 {w:"私",r:"わたし",say:"わたし",mean:"Yo",ej:"私は学生です。",ejr:"わたしは がくせいです",ejt:"Soy estudiante.",lvl:"N5"},
 {w:"学生",r:"がくせい",say:"がくせい",mean:"Estudiante",ej:"彼は学生です。",ejr:"かれは がくせいです",ejt:"Él es estudiante.",lvl:"N5"},
 {w:"先生",r:"せんせい",say:"せんせい",mean:"Profesor / profesora",ej:"先生、こんにちは。",ejr:"せんせい、こんにちは",ejt:"Hola, profesor.",lvl:"N5"},
 {w:"友だち",r:"ともだち",say:"ともだち",mean:"Amigo / amiga",ej:"友だちと話します。",ejr:"ともだちと はなします",ejt:"Hablo con un amigo.",lvl:"N5"},
 {w:"学校",r:"がっこう",say:"がっこう",mean:"Escuela",ej:"学校へ行きます。",ejr:"がっこうへ いきます",ejt:"Voy a la escuela.",lvl:"N5"},
 {w:"日本",r:"にほん",say:"にほん",mean:"Japón",ej:"ここは日本です。",ejr:"ここは にほんです",ejt:"Esto es Japón.",lvl:"N5"},
 {w:"食べる",r:"たべる",say:"たべる",mean:"Comer",ej:"ご飯を食べます。",ejr:"ごはんを たべます",ejt:"Como (arroz).",lvl:"N5"},
 {w:"飲む",r:"のむ",say:"のむ",mean:"Beber",ej:"お茶を飲みます。",ejr:"おちゃを のみます",ejt:"Bebo té.",lvl:"N5"},
 {w:"行く",r:"いく",say:"いく",mean:"Ir",ej:"駅へ行きます。",ejr:"えきへ いきます",ejt:"Voy a la estación.",lvl:"N5"},
 {w:"来る",r:"くる",say:"くる",mean:"Venir",ej:"友だちが来ます。",ejr:"ともだちが きます",ejt:"Viene un amigo.",lvl:"N5"},
 {w:"見る",r:"みる",say:"みる",mean:"Ver · mirar",ej:"テレビを見ます。",ejr:"テレビを みます",ejt:"Veo la tele.",lvl:"N5"},
 {w:"聞く",r:"きく",say:"きく",mean:"Escuchar · preguntar",ej:"音楽を聞きます。",ejr:"おんがくを ききます",ejt:"Escucho música.",lvl:"N5"},
 {w:"話す",r:"はなす",say:"はなす",mean:"Hablar",ej:"日本語を話します。",ejr:"にほんごを はなします",ejt:"Hablo japonés.",lvl:"N5"},
 {w:"読む",r:"よむ",say:"よむ",mean:"Leer",ej:"本を読みます。",ejr:"ほんを よみます",ejt:"Leo un libro.",lvl:"N5"},
 {w:"書く",r:"かく",say:"かく",mean:"Escribir",ej:"手紙を書きます。",ejr:"てがみを かきます",ejt:"Escribo una carta.",lvl:"N5"},
 {w:"大きい",r:"おおきい",say:"おおきい",mean:"Grande",ej:"大きい家です。",ejr:"おおきい いえです",ejt:"Es una casa grande.",lvl:"N5"},
 {w:"小さい",r:"ちいさい",say:"ちいさい",mean:"Pequeño",ej:"小さい犬です。",ejr:"ちいさい いぬです",ejt:"Es un perro pequeño.",lvl:"N5"},
 {w:"水",r:"みず",say:"みず",mean:"Agua",ej:"水を飲みます。",ejr:"みずを のみます",ejt:"Bebo agua.",lvl:"N5"},
 {w:"本",r:"ほん",say:"ほん",mean:"Libro",ej:"本を読みます。",ejr:"ほんを よみます",ejt:"Leo un libro.",lvl:"N5"},
 {w:"今日",r:"きょう",say:"きょう",mean:"Hoy",ej:"今日は寒いです。",ejr:"きょうは さむいです",ejt:"Hoy hace frío.",lvl:"N5"},
 {w:"お金",r:"おかね",say:"おかね",mean:"Dinero",ej:"お金がありません。",ejr:"おかねが ありません",ejt:"No tengo dinero.",lvl:"N5"},
 {w:"家",r:"いえ",say:"いえ",mean:"Casa · hogar",ej:"家へ帰ります。",ejr:"いえへ かえります",ejt:"Vuelvo a casa.",lvl:"N5"},
 {w:"時間",r:"じかん",say:"じかん",mean:"Tiempo · hora",ej:"時間がありません。",ejr:"じかんが ありません",ejt:"No tengo tiempo.",lvl:"N5"},
 {w:"電話",r:"でんわ",say:"でんわ",mean:"Teléfono",ej:"電話をします。",ejr:"でんわを します",ejt:"Hago una llamada.",lvl:"N5"},
 {w:"仕事",r:"しごと",say:"しごと",mean:"Trabajo · empleo",ej:"仕事は何ですか。",ejr:"しごとは なんですか",ejt:"¿En qué trabajas?",lvl:"N5"},
 {w:"部屋",r:"へや",say:"へや",mean:"Habitación",ej:"部屋は静かです。",ejr:"へやは しずかです",ejt:"La habitación es tranquila.",lvl:"N5"},
 {w:"会社",r:"かいしゃ",say:"かいしゃ",mean:"Empresa",ej:"会社へ行きます。",ejr:"かいしゃへ いきます",ejt:"Voy a la empresa.",lvl:"N5"},
 {w:"お茶",r:"おちゃ",say:"おちゃ",mean:"Té",ej:"お茶を飲みます。",ejr:"おちゃを のみます",ejt:"Bebo té.",lvl:"N5"},
 {w:"ご飯",r:"ごはん",say:"ごはん",mean:"Arroz · comida",ej:"ご飯を食べます。",ejr:"ごはんを たべます",ejt:"Como (arroz).",lvl:"N5"},
 {w:"肉",r:"にく",say:"にく",mean:"Carne",ej:"肉が好きです。",ejr:"にくが すきです",ejt:"Me gusta la carne.",lvl:"N5"},
 {w:"魚",r:"さかな",say:"さかな",mean:"Pescado · pez",ej:"魚を食べます。",ejr:"さかなを たべます",ejt:"Como pescado.",lvl:"N5"},
 {w:"犬",r:"いぬ",say:"いぬ",mean:"Perro",ej:"犬がいます。",ejr:"いぬが います",ejt:"Hay un perro.",lvl:"N5"},
 {w:"猫",r:"ねこ",say:"ねこ",mean:"Gato",ej:"猫が好きです。",ejr:"ねこが すきです",ejt:"Me gustan los gatos.",lvl:"N5"},
 {w:"お父さん",r:"おとうさん",say:"おとうさん",mean:"Padre (de otro)",ej:"お父さんは先生です。",ejr:"おとうさんは せんせいです",ejt:"Su padre es profesor.",lvl:"N5"},
 {w:"お母さん",r:"おかあさん",say:"おかあさん",mean:"Madre (de otro)",ej:"お母さんは元気です。",ejr:"おかあさんは げんきです",ejt:"Su madre está bien.",lvl:"N5"},
 {w:"音楽",r:"おんがく",say:"おんがく",mean:"Música",ej:"音楽を聞きます。",ejr:"おんがくを ききます",ejt:"Escucho música.",lvl:"N5"},
 {w:"写真",r:"しゃしん",say:"しゃしん",mean:"Foto",ej:"写真を撮ります。",ejr:"しゃしんを とります",ejt:"Hago una foto.",lvl:"N5"},
 {w:"旅行",r:"りょこう",say:"りょこう",mean:"Viaje",ej:"旅行は楽しいです。",ejr:"りょこうは たのしいです",ejt:"El viaje es divertido.",lvl:"N5"},
 {w:"英語",r:"えいご",say:"えいご",mean:"Inglés (idioma)",ej:"英語を話します。",ejr:"えいごを はなします",ejt:"Hablo inglés.",lvl:"N5"},
 {w:"公園",r:"こうえん",say:"こうえん",mean:"Parque",ej:"公園を歩きます。",ejr:"こうえんを あるきます",ejt:"Paseo por el parque.",lvl:"N5"},
 {w:"する",r:"する",say:"する",mean:"Hacer",ej:"勉強をします。",ejr:"べんきょうを します",ejt:"Estudio.",lvl:"N5"},
 {w:"買う",r:"かう",say:"かう",mean:"Comprar",ej:"パンを買います。",ejr:"パンを かいます",ejt:"Compro pan.",lvl:"N5"},
 {w:"待つ",r:"まつ",say:"まつ",mean:"Esperar",ej:"ちょっと待ってください。",ejr:"ちょっと まってください",ejt:"Espera un momento, por favor.",lvl:"N5"},
 {w:"帰る",r:"かえる",say:"かえる",mean:"Volver (a casa)",ej:"何時に帰りますか。",ejr:"なんじに かえりますか",ejt:"¿A qué hora vuelves?",lvl:"N5"},
 {w:"起きる",r:"おきる",say:"おきる",mean:"Levantarse · despertarse",ej:"7時に起きます。",ejr:"しちじに おきます",ejt:"Me levanto a las 7.",lvl:"N5"},
 {w:"寝る",r:"ねる",say:"ねる",mean:"Dormir · acostarse",ej:"11時に寝ます。",ejr:"じゅういちじに ねます",ejt:"Me acuesto a las 11.",lvl:"N5"},
 {w:"作る",r:"つくる",say:"つくる",mean:"Hacer · fabricar",ej:"料理を作ります。",ejr:"りょうりを つくります",ejt:"Cocino.",lvl:"N5"},
 {w:"使う",r:"つかう",say:"つかう",mean:"Usar",ej:"はしを使います。",ejr:"はしを つかいます",ejt:"Uso palillos.",lvl:"N5"},
 {w:"教える",r:"おしえる",say:"おしえる",mean:"Enseñar",ej:"日本語を教えます。",ejr:"にほんごを おしえます",ejt:"Enseño japonés.",lvl:"N5"},
 {w:"習う",r:"ならう",say:"ならう",mean:"Aprender",ej:"英語を習います。",ejr:"えいごを ならいます",ejt:"Aprendo inglés.",lvl:"N5"},
 {w:"勉強する",r:"べんきょうする",say:"べんきょうする",mean:"Estudiar",ej:"毎日勉強します。",ejr:"まいにち べんきょうします",ejt:"Estudio cada día.",lvl:"N5"},
 {w:"分かる",r:"わかる",say:"わかる",mean:"Entender",ej:"日本語が分かります。",ejr:"にほんごが わかります",ejt:"Entiendo japonés.",lvl:"N5"},
 {w:"知る",r:"しる",say:"しる",mean:"Saber · conocer",ej:"名前を知っています。",ejr:"なまえを しっています",ejt:"Sé su nombre.",lvl:"N5"},
 {w:"乗る",r:"のる",say:"のる",mean:"Subir(se) · montar",ej:"電車に乗ります。",ejr:"でんしゃに のります",ejt:"Subo al tren.",lvl:"N5"},
 {w:"歩く",r:"あるく",say:"あるく",mean:"Caminar",ej:"駅まで歩きます。",ejr:"えきまで あるきます",ejt:"Camino hasta la estación.",lvl:"N5"},
 {w:"走る",r:"はしる",say:"はしる",mean:"Correr",ej:"公園を走ります。",ejr:"こうえんを はしります",ejt:"Corro por el parque.",lvl:"N5"},
 {w:"持つ",r:"もつ",say:"もつ",mean:"Tener · sostener",ej:"かばんを持ちます。",ejr:"かばんを もちます",ejt:"Llevo un bolso.",lvl:"N5"},
 {w:"撮る",r:"とる",say:"とる",mean:"Tomar (foto)",ej:"ここで写真を撮ります。",ejr:"ここで しゃしんを とります",ejt:"Hago una foto aquí.",lvl:"N5"},
 {w:"いい",r:"いい",say:"いい",mean:"Bueno",ej:"いい天気ですね。",ejr:"いい てんきですね",ejt:"Hace buen tiempo, ¿verdad?",lvl:"N5"},
 {w:"悪い",r:"わるい",say:"わるい",mean:"Malo",ej:"天気が悪いです。",ejr:"てんきが わるいです",ejt:"Hace mal tiempo.",lvl:"N5"},
 {w:"暑い",r:"あつい",say:"あつい",mean:"Caluroso (clima)",ej:"今日は暑いです。",ejr:"きょうは あついです",ejt:"Hoy hace calor.",lvl:"N5"},
 {w:"寒い",r:"さむい",say:"さむい",mean:"Frío (clima)",ej:"冬は寒いです。",ejr:"ふゆは さむいです",ejt:"En invierno hace frío.",lvl:"N5"},
 {w:"楽しい",r:"たのしい",say:"たのしい",mean:"Divertido · agradable",ej:"パーティーは楽しいです。",ejr:"パーティーは たのしいです",ejt:"La fiesta es divertida.",lvl:"N5"},
 {w:"面白い",r:"おもしろい",say:"おもしろい",mean:"Interesante · gracioso",ej:"この本は面白いです。",ejr:"この ほんは おもしろいです",ejt:"Este libro es interesante.",lvl:"N5"},
 {w:"難しい",r:"むずかしい",say:"むずかしい",mean:"Difícil",ej:"漢字は難しいです。",ejr:"かんじは むずかしいです",ejt:"El kanji es difícil.",lvl:"N5"},
 {w:"静か",r:"しずか",say:"しずか",mean:"Tranquilo · silencioso",ej:"図書館は静かです。",ejr:"としょかんは しずかです",ejt:"La biblioteca es tranquila.",lvl:"N5"},
 {w:"元気",r:"げんき",say:"げんき",mean:"Sano · con energía",ej:"元気ですか。",ejr:"げんきですか",ejt:"¿Cómo estás?",lvl:"N5"},
 {w:"好き",r:"すき",say:"すき",mean:"Que gusta",ej:"日本が好きです。",ejr:"にほんが すきです",ejt:"Me gusta Japón.",lvl:"N5"},
 {w:"きれい",r:"きれい",say:"きれい",mean:"Bonito · limpio",ej:"花がきれいです。",ejr:"はなが きれいです",ejt:"Las flores son bonitas.",lvl:"N5"},
 {w:"有名",r:"ゆうめい",say:"ゆうめい",mean:"Famoso",ej:"有名な店です。",ejr:"ゆうめいな みせです",ejt:"Es una tienda famosa.",lvl:"N5"},
 {w:"朝",r:"あさ",say:"あさ",mean:"Mañana (parte del día)",ej:"朝ご飯を食べます。",ejr:"あさごはんを たべます",ejt:"Desayuno.",lvl:"N5"},
 {w:"昼",r:"ひる",say:"ひる",mean:"Mediodía · tarde",ej:"昼に休みます。",ejr:"ひるに やすみます",ejt:"Descanso al mediodía.",lvl:"N5"},
 {w:"夜",r:"よる",say:"よる",mean:"Noche",ej:"夜は寒いです。",ejr:"よるは さむいです",ejt:"De noche hace frío.",lvl:"N5"},
 {w:"明日",r:"あした",say:"あした",mean:"Mañana (día siguiente)",ej:"明日は休みです。",ejr:"あしたは やすみです",ejt:"Mañana es día libre.",lvl:"N5"},
 {w:"昨日",r:"きのう",say:"きのう",mean:"Ayer",ej:"昨日映画を見ました。",ejr:"きのう えいがを みました",ejt:"Ayer vi una película.",lvl:"N5"},
 {w:"毎日",r:"まいにち",say:"まいにち",mean:"Cada día",ej:"毎日勉強します。",ejr:"まいにち べんきょうします",ejt:"Estudio cada día.",lvl:"N5"},
 {w:"来年",r:"らいねん",say:"らいねん",mean:"El año que viene",ej:"来年日本へ行きます。",ejr:"らいねん にほんへ いきます",ejt:"El año que viene voy a Japón.",lvl:"N5"},
 {w:"週末",r:"しゅうまつ",say:"しゅうまつ",mean:"Fin de semana",ej:"週末は忙しいです。",ejr:"しゅうまつは いそがしいです",ejt:"El finde estoy ocupado.",lvl:"N5"},
 {w:"大学",r:"だいがく",say:"だいがく",mean:"Universidad",ej:"大学で勉強します。",ejr:"だいがくで べんきょうします",ejt:"Estudio en la universidad.",lvl:"N5"},
 {w:"病院",r:"びょういん",say:"びょういん",mean:"Hospital",ej:"病院へ行きます。",ejr:"びょういんへ いきます",ejt:"Voy al hospital.",lvl:"N5"},
 {w:"銀行",r:"ぎんこう",say:"ぎんこう",mean:"Banco",ej:"銀行はどこですか。",ejr:"ぎんこうは どこですか",ejt:"¿Dónde está el banco?",lvl:"N5"},
 {w:"図書館",r:"としょかん",say:"としょかん",mean:"Biblioteca",ej:"図書館で本を読みます。",ejr:"としょかんで ほんを よみます",ejt:"Leo en la biblioteca.",lvl:"N5"},
 {w:"レストラン",r:"レストラン",say:"レストラン",mean:"Restaurante",ej:"レストランで食べます。",ejr:"レストランで たべます",ejt:"Como en un restaurante.",lvl:"N5"},
 {w:"デパート",r:"デパート",say:"デパート",mean:"Grandes almacenes",ej:"デパートで買い物します。",ejr:"デパートで かいものします",ejt:"Compro en los grandes almacenes.",lvl:"N5"},
 {w:"空港",r:"くうこう",say:"くうこう",mean:"Aeropuerto",ej:"空港で待ちます。",ejr:"くうこうで まちます",ejt:"Espero en el aeropuerto.",lvl:"N5"},
 {w:"パン",r:"パン",say:"パン",mean:"Pan",ej:"パンを食べます。",ejr:"パンを たべます",ejt:"Como pan.",lvl:"N5"},
 {w:"卵",r:"たまご",say:"たまご",mean:"Huevo",ej:"卵を買います。",ejr:"たまごを かいます",ejt:"Compro huevos.",lvl:"N5"},
 {w:"野菜",r:"やさい",say:"やさい",mean:"Verdura",ej:"野菜が好きです。",ejr:"やさいが すきです",ejt:"Me gustan las verduras.",lvl:"N5"},
 {w:"果物",r:"くだもの",say:"くだもの",mean:"Fruta",ej:"果物を食べます。",ejr:"くだものを たべます",ejt:"Como fruta.",lvl:"N5"},
 {w:"コーヒー",r:"コーヒー",say:"コーヒー",mean:"Café",ej:"コーヒーを飲みます。",ejr:"コーヒーを のみます",ejt:"Bebo café.",lvl:"N5"},
 {w:"お酒",r:"おさけ",say:"おさけ",mean:"Alcohol · sake",ej:"お酒を飲みません。",ejr:"おさけを のみません",ejt:"No bebo alcohol.",lvl:"N5"},
 {w:"彼",r:"かれ",say:"かれ",mean:"Él · novio",ej:"彼は学生です。",ejr:"かれは がくせいです",ejt:"Él es estudiante.",lvl:"N5"},
 {w:"彼女",r:"かのじょ",say:"かのじょ",mean:"Ella · novia",ej:"彼女は先生です。",ejr:"かのじょは せんせいです",ejt:"Ella es profesora.",lvl:"N5"},
 {w:"家族",r:"かぞく",say:"かぞく",mean:"Familia",ej:"家族は四人です。",ejr:"かぞくは よにんです",ejt:"Mi familia somos cuatro.",lvl:"N5"},
 {w:"子ども",r:"こども",say:"こども",mean:"Niño · hijo",ej:"子どもが二人います。",ejr:"こどもが ふたり います",ejt:"Tengo dos hijos.",lvl:"N5"},
 {w:"速い",r:"はやい",say:"はやい",mean:"Rápido",ej:"新幹線は速いです。",ejr:"しんかんせんは はやいです",ejt:"El shinkansen es rápido.",lvl:"N5"},
 {w:"遅い",r:"おそい",say:"おそい",mean:"Lento · tarde",ej:"バスは遅いです。",ejr:"バスは おそいです",ejt:"El autobús es lento.",lvl:"N5"},
 {w:"忙しい",r:"いそがしい",say:"いそがしい",mean:"Ocupado",ej:"今日は忙しいです。",ejr:"きょうは いそがしいです",ejt:"Hoy estoy ocupado.",lvl:"N5"},
 {w:"かわいい",r:"かわいい",say:"かわいい",mean:"Mono · bonito",ej:"猫はかわいいです。",ejr:"ねこは かわいいです",ejt:"El gato es mono.",lvl:"N5"},
 {w:"便利",r:"べんり",say:"べんり",mean:"Práctico · cómodo",ej:"この店は便利です。",ejr:"このみせは べんりです",ejt:"Esta tienda es práctica.",lvl:"N5"},
 {w:"暇",r:"ひま",say:"ひま",mean:"Tiempo libre · libre",ej:"今日は暇です。",ejr:"きょうは ひまです",ejt:"Hoy estoy libre.",lvl:"N5"},
 {w:"大切",r:"たいせつ",say:"たいせつ",mean:"Importante",ej:"家族は大切です。",ejr:"かぞくは たいせつです",ejt:"La familia es importante.",lvl:"N5"},
 {w:"とても",r:"とても",say:"とても",mean:"Muy",ej:"とても面白いです。",ejr:"とても おもしろいです",ejt:"Es muy interesante.",lvl:"N5"},
 {w:"たくさん",r:"たくさん",say:"たくさん",mean:"Mucho · muchos",ej:"本がたくさんあります。",ejr:"ほんが たくさん あります",ejt:"Hay muchos libros.",lvl:"N5"},
 {w:"ちょっと",r:"ちょっと",say:"ちょっと",mean:"Un poco · un momento",ej:"ちょっと待ってください。",ejr:"ちょっと まってください",ejt:"Espera un poco, por favor.",lvl:"N5"},
 {w:"よく",r:"よく",say:"よく",mean:"A menudo · bien",ej:"よく音楽を聞きます。",ejr:"よく おんがくを ききます",ejt:"Escucho música a menudo.",lvl:"N5"},
 {w:"あまり",r:"あまり",say:"あまり",mean:"No mucho (con negativo)",ej:"あまり分かりません。",ejr:"あまり わかりません",ejt:"No entiendo mucho.",lvl:"N5"},
 {w:"開ける",r:"あける",say:"あける",mean:"Abrir",ej:"窓を開けます。",ejr:"まどを あけます",ejt:"Abro la ventana.",lvl:"N5"},
 {w:"閉める",r:"しめる",say:"しめる",mean:"Cerrar",ej:"ドアを閉めます。",ejr:"ドアを しめます",ejt:"Cierro la puerta.",lvl:"N5"},
 {w:"始まる",r:"はじまる",say:"はじまる",mean:"Empezar (algo)",ej:"授業が始まります。",ejr:"じゅぎょうが はじまります",ejt:"Empieza la clase.",lvl:"N5"},
 {w:"終わる",r:"おわる",say:"おわる",mean:"Terminar (algo)",ej:"仕事が終わります。",ejr:"しごとが おわります",ejt:"Termina el trabajo.",lvl:"N5"},
 {w:"着る",r:"きる",say:"きる",mean:"Ponerse · vestir",ej:"コートを着ます。",ejr:"コートを きます",ejt:"Me pongo el abrigo.",lvl:"N5"},
 {w:"洗う",r:"あらう",say:"あらう",mean:"Lavar",ej:"手を洗います。",ejr:"てを あらいます",ejt:"Me lavo las manos.",lvl:"N5"},
 {w:"泳ぐ",r:"およぐ",say:"およぐ",mean:"Nadar",ej:"海で泳ぎます。",ejr:"うみで およぎます",ejt:"Nado en el mar.",lvl:"N5"},
 {w:"遊ぶ",r:"あそぶ",say:"あそぶ",mean:"Jugar · divertirse",ej:"公園で遊びます。",ejr:"こうえんで あそびます",ejt:"Juego en el parque.",lvl:"N5"},
 {w:"質問",r:"しつもん",say:"しつもん",mean:"Pregunta",ej:"質問があります。",ejr:"しつもんが あります",ejt:"Tengo una pregunta.",lvl:"N5"},
 {w:"言葉",r:"ことば",say:"ことば",mean:"Palabra · idioma",ej:"この言葉は難しいです。",ejr:"このことばは むずかしいです",ejt:"Esta palabra es difícil.",lvl:"N5"},
 {w:"切符",r:"きっぷ",say:"きっぷ",mean:"Billete · ticket",ej:"切符を買います。",ejr:"きっぷを かいます",ejt:"Compro un billete.",lvl:"N5"},
 {w:"かばん",r:"かばん",say:"かばん",mean:"Bolso · maletín",ej:"かばんを持ちます。",ejr:"かばんを もちます",ejt:"Llevo un bolso.",lvl:"N5"},
 {w:"服",r:"ふく",say:"ふく",mean:"Ropa",ej:"服を買います。",ejr:"ふくを かいます",ejt:"Compro ropa.",lvl:"N5"},
 {w:"頭",r:"あたま",say:"あたま",mean:"Cabeza",ej:"頭がいいです。",ejr:"あたまが いいです",ejt:"Es listo (buena cabeza).",lvl:"N5"},
 {w:"顔",r:"かお",say:"かお",mean:"Cara",ej:"顔を洗います。",ejr:"かおを あらいます",ejt:"Me lavo la cara.",lvl:"N5"},
 {w:"耳",r:"みみ",say:"みみ",mean:"Oreja · oído",ej:"耳で聞きます。",ejr:"みみで ききます",ejt:"Escucho con los oídos.",lvl:"N5"},
 {w:"歯",r:"は",say:"は",mean:"Diente",ej:"歯が白いです。",ejr:"はが しろいです",ejt:"Tiene los dientes blancos.",lvl:"N5"},
 {w:"体",r:"からだ",say:"からだ",mean:"Cuerpo",ej:"体が大きいです。",ejr:"からだが おおきいです",ejt:"Tiene un cuerpo grande.",lvl:"N5"},
 {w:"お腹",r:"おなか",say:"おなか",mean:"Barriga · estómago",ej:"お腹がすきました。",ejr:"おなかが すきました",ejt:"Tengo hambre.",lvl:"N5"},
 {w:"赤",r:"あか",say:"あか",mean:"Rojo",ej:"赤が好きです。",ejr:"あかが すきです",ejt:"Me gusta el rojo.",lvl:"N5"},
 {w:"青",r:"あお",say:"あお",mean:"Azul",ej:"空は青いです。",ejr:"そらは あおいです",ejt:"El cielo es azul.",lvl:"N5"},
 {w:"黒",r:"くろ",say:"くろ",mean:"Negro",ej:"黒い猫です。",ejr:"くろい ねこです",ejt:"Es un gato negro.",lvl:"N5"},
 {w:"黄色",r:"きいろ",say:"きいろ",mean:"Amarillo",ej:"黄色い花です。",ejr:"きいろい はなです",ejt:"Es una flor amarilla.",lvl:"N5"},
 {w:"緑",r:"みどり",say:"みどり",mean:"Verde",ej:"緑が好きです。",ejr:"みどりが すきです",ejt:"Me gusta el verde.",lvl:"N5"},
 {w:"雪",r:"ゆき",say:"ゆき",mean:"Nieve",ej:"雪が降ります。",ejr:"ゆきが ふります",ejt:"Nieva.",lvl:"N5"},
 {w:"風",r:"かぜ",say:"かぜ",mean:"Viento",ej:"今日は風がありません。",ejr:"きょうは かぜが ありません",ejt:"Hoy no hay viento.",lvl:"N5"},
 {w:"海",r:"うみ",say:"うみ",mean:"Mar",ej:"海はきれいです。",ejr:"うみは きれいです",ejt:"El mar es bonito.",lvl:"N5"},
 {w:"花",r:"はな",say:"はな",mean:"Flor",ej:"花を買います。",ejr:"はなを かいます",ejt:"Compro flores.",lvl:"N5"},
 {w:"窓",r:"まど",say:"まど",mean:"Ventana",ej:"窓が大きいです。",ejr:"まどが おおきいです",ejt:"La ventana es grande.",lvl:"N5"},
 {w:"椅子",r:"いす",say:"いす",mean:"Silla",ej:"椅子に座ります。",ejr:"いすに すわります",ejt:"Me siento en la silla.",lvl:"N5"},
 {w:"机",r:"つくえ",say:"つくえ",mean:"Mesa · escritorio",ej:"机の上に本があります。",ejr:"つくえの うえに ほんが あります",ejt:"Hay un libro sobre la mesa.",lvl:"N5"},
 {w:"テレビ",r:"テレビ",say:"テレビ",mean:"Televisión",ej:"テレビを見ます。",ejr:"テレビを みます",ejt:"Veo la tele.",lvl:"N5"},
 {w:"新聞",r:"しんぶん",say:"しんぶん",mean:"Periódico",ej:"新聞を読みます。",ejr:"しんぶんを よみます",ejt:"Leo el periódico.",lvl:"N5"},
 {w:"手紙",r:"てがみ",say:"てがみ",mean:"Carta",ej:"手紙を書きます。",ejr:"てがみを かきます",ejt:"Escribo una carta.",lvl:"N5"},
 {w:"傘",r:"かさ",say:"かさ",mean:"Paraguas",ej:"傘を持ちます。",ejr:"かさを もちます",ejt:"Llevo un paraguas.",lvl:"N5"},
 {w:"時計",r:"とけい",say:"とけい",mean:"Reloj",ej:"時計を見ます。",ejr:"とけいを みます",ejt:"Miro el reloj.",lvl:"N5"},
 {w:"いつも",r:"いつも",say:"いつも",mean:"Siempre",ej:"いつも早く起きます。",ejr:"いつも はやく おきます",ejt:"Siempre me levanto pronto.",lvl:"N5"},
 {w:"ときどき",r:"ときどき",say:"ときどき",mean:"A veces",ej:"ときどき映画を見ます。",ejr:"ときどき えいがを みます",ejt:"A veces veo películas.",lvl:"N5"},
 {w:"すぐ",r:"すぐ",say:"すぐ",mean:"Enseguida · pronto",ej:"すぐ行きます。",ejr:"すぐ いきます",ejt:"Voy enseguida.",lvl:"N5"},
 {w:"また",r:"また",say:"また",mean:"Otra vez · además",ej:"また会いましょう。",ejr:"また あいましょう",ejt:"Hasta la próxima.",lvl:"N5"},
 {w:"座る",r:"すわる",say:"すわる",mean:"Sentarse",ej:"ここに座ってください。",ejr:"ここに すわってください",ejt:"Siéntate aquí, por favor.",lvl:"N5"},
 {w:"借りる",r:"かりる",say:"かりる",mean:"Pedir prestado",ej:"本を借ります。",ejr:"ほんを かります",ejt:"Tomo prestado un libro.",lvl:"N5"},
 {w:"貸す",r:"かす",say:"かす",mean:"Prestar",ej:"お金を貸します。",ejr:"おかねを かします",ejt:"Presto dinero.",lvl:"N5"},
 {w:"返す",r:"かえす",say:"かえす",mean:"Devolver",ej:"本を返します。",ejr:"ほんを かえします",ejt:"Devuelvo el libro.",lvl:"N5"},
 {w:"消す",r:"けす",say:"けす",mean:"Apagar · borrar",ej:"電気を消します。",ejr:"でんきを けします",ejt:"Apago la luz.",lvl:"N5"},
 {w:"押す",r:"おす",say:"おす",mean:"Empujar · pulsar",ej:"ボタンを押します。",ejr:"ボタンを おします",ejt:"Pulso el botón.",lvl:"N5"},
 {w:"着く",r:"つく",say:"つく",mean:"Llegar",ej:"駅に着きます。",ejr:"えきに つきます",ejt:"Llego a la estación.",lvl:"N5"},
 {w:"住む",r:"すむ",say:"すむ",mean:"Vivir · residir",ej:"東京に住んでいます。",ejr:"とうきょうに すんでいます",ejt:"Vivo en Tokio.",lvl:"N5"},
 {w:"働く",r:"はたらく",say:"はたらく",mean:"Trabajar",ej:"銀行で働きます。",ejr:"ぎんこうで はたらきます",ejt:"Trabajo en un banco.",lvl:"N5"},
 {w:"歌う",r:"うたう",say:"うたう",mean:"Cantar",ej:"歌を歌います。",ejr:"うたを うたいます",ejt:"Canto una canción.",lvl:"N5"}
],

/* ---------------- GRAMÁTICA ---------------- */
grammar: [
 /* ===== N5 ===== */
 {pat:"〜です",mean:"Ser / estar (cortés)",exp:"です va al final para afirmar de forma educada: A は B です significa A es B. Su forma informal es だ.",ej:"わたしは学生です。",ejr:"わたしは がくせいです",ejt:"Soy estudiante.",err:"En lenguaje cortés no se puede omitir です.",lvl:"N5"},
 {pat:"は",mean:"Partícula de tema (se lee wa)",exp:"は marca el tema: de lo que se habla. Aunque se escribe は, se pronuncia wa.",ej:"これは本です。",ejr:"これは ほんです",ejt:"Esto es un libro.",err:"Pronunciarla ha en vez de wa, o confundirla con が.",lvl:"N5"},
 {pat:"が",mean:"Sujeto / información nueva",exp:"が marca el sujeto, sobre todo cuando presentas información nueva o respondes a quién o qué.",ej:"猫がいます。",ejr:"ねこが います",ejt:"Hay un gato.",err:"Usar は cuando en realidad presentas algo por primera vez.",lvl:"N5"},
 {pat:"を",mean:"Objeto directo (se lee o)",exp:"を marca lo que recibe la acción del verbo. Se escribe を pero se lee o.",ej:"パンを食べます。",ejr:"パンを たべます",ejt:"Como pan.",err:"Escribir お en lugar de を.",lvl:"N5"},
 {pat:"に",mean:"Destino · momento · existencia",exp:"に indica el punto al que se llega, el momento exacto, o el lugar donde algo existe: 7時に, 学校に行く.",ej:"学校に行きます。",ejr:"がっこうに いきます",ejt:"Voy a la escuela.",err:"Confundir に (destino) con で (lugar de acción).",lvl:"N5"},
 {pat:"で",mean:"Lugar de acción · medio",exp:"で indica dónde ocurre una acción o con qué medio se hace: 図書館で勉強する, バスで行く.",ej:"図書館で勉強します。",ejr:"としょかんで べんきょうします",ejt:"Estudio en la biblioteca.",err:"Usar に para el lugar donde realizas una acción.",lvl:"N5"},
 {pat:"へ",mean:"Dirección (se lee e)",exp:"へ indica la dirección hacia la que te mueves. Se escribe へ pero se lee e. Parecido a に de destino.",ej:"東京へ行きます。",ejr:"とうきょうへ いきます",ejt:"Voy hacia Tokio.",err:"Leerla he en vez de e.",lvl:"N5"},
 {pat:"の",mean:"Posesión · unión de nombres",exp:"の une dos sustantivos: el primero describe o posee al segundo. わたしの本 = mi libro.",ej:"わたしの本です。",ejr:"わたしの ほんです",ejt:"Es mi libro.",err:"Olvidar の entre dos sustantivos.",lvl:"N5"},
 {pat:"と",mean:"Y (lista completa) · con",exp:"と une sustantivos en una lista completa (A と B) y también significa con alguien.",ej:"パンとたまごを食べます。",ejr:"パンと たまごを たべます",ejt:"Como pan y huevo.",err:"Usar と para listas incompletas; para esas se usa や.",lvl:"N5"},
 {pat:"も",mean:"También / tampoco",exp:"も sustituye a は o が y significa también. En frases negativas significa tampoco.",ej:"わたしも学生です。",ejr:"わたしも がくせいです",ejt:"Yo también soy estudiante.",err:"Mantener は o が junto con も; も los reemplaza.",lvl:"N5"},
 {pat:"か",mean:"Partícula de pregunta",exp:"か al final convierte la frase en pregunta. En japonés cortés no hace falta signo de interrogación.",ej:"学生ですか。",ejr:"がくせいですか",ejt:"¿Eres estudiante?",err:"Olvidar か y depender solo del tono.",lvl:"N5"},
 {pat:"から〜まで",mean:"Desde ~ hasta ~",exp:"から marca el inicio (desde) y まで el final (hasta), en tiempo o en lugar.",ej:"9時から5時まで働きます。",ejr:"くじから ごじまで はたらきます",ejt:"Trabajo de 9 a 5.",err:"Invertir el orden de las partículas.",lvl:"N5"},
 {pat:"〜ません",mean:"Negativo cortés del verbo",exp:"La forma ます se hace negativa cambiándola por ません: 行きます → 行きません (no voy).",ej:"今日は行きません。",ejr:"きょうは いきません",ejt:"Hoy no voy.",err:"Negar con ない en contexto cortés en vez de ません.",lvl:"N5"},
 {pat:"〜たいです",mean:"Querer (hacer algo)",exp:"Se quita ます del verbo y se añade たいです para expresar el deseo del hablante: 飲みます → 飲みたいです.",ej:"水が飲みたいです。",ejr:"みずが のみたいです",ejt:"Quiero beber agua.",err:"Usarlo para deseos de otras personas; たい es para el hablante.",lvl:"N5"},
 {pat:"〜てください",mean:"Por favor, haz ~",exp:"La forma て del verbo + ください pide algo de forma educada: 見てください = mira, por favor.",ej:"名前を書いてください。",ejr:"なまえを かいてください",ejt:"Escribe tu nombre, por favor.",err:"Equivocarse al formar la forma て del verbo.",lvl:"N5"},
 {pat:"い-adjetivos",mean:"Adjetivos terminados en い",exp:"Modifican directamente al sustantivo (大きい車) y se niegan cambiando い por くない: 大きい → 大きくない.",ej:"これは大きい車です。",ejr:"これは おおきい くるまです",ejt:"Este es un coche grande.",err:"Poner な después de un adjetivo い.",lvl:"N5"},
 {pat:"な-adjetivos",mean:"Adjetivos que necesitan な",exp:"Necesitan な para unirse a un sustantivo (きれいな花) pero NO la usan delante de です (きれいです).",ej:"きれいな花ですね。",ejr:"きれいな はなですね",ejt:"Es una flor bonita, ¿verdad?",err:"Decir きれいなです en vez de きれいです.",lvl:"N5"},
 {pat:"〜ましょう",mean:"Hagamos ~ (invitación)",exp:"Se cambia ます por ましょう para proponer hacer algo juntos: 行きましょう = vamos.",ej:"一緒に行きましょう。",ejr:"いっしょに いきましょう",ejt:"Vamos juntos.",err:"Confundirlo con ましょうか, que ofrece ayuda.",lvl:"N5"},
 {pat:"あります / います",mean:"Existir (cosas / seres vivos)",exp:"あります para cosas y plantas; います para personas y animales. El sujeto va con が.",ej:"本があります。",ejr:"ほんが あります",ejt:"Hay un libro.",err:"Usar あります con personas o animales.",lvl:"N5"},
 {pat:"〜が好きです",mean:"Me gusta ~",exp:"好き es un adjetivo な y lo que gusta se marca con が, no con を: すしが好きです.",ej:"すしが好きです。",ejr:"すしが すきです",ejt:"Me gusta el sushi.",err:"Marcar lo que gusta con を en lugar de が.",lvl:"N5"},
 {pat:"〜でした / ではありません",mean:"Pasado y negativo de です",exp:"です en pasado es でした; en negativo, ではありません (coloquial じゃない). 学生でした = era estudiante.",ej:"きのうは休みでした。",ejr:"きのうは やすみでした",ejt:"Ayer fue día libre.",err:"Combinar です con でした o con じゃない (no se juntan).",lvl:"N5"},
 {pat:"〜ました / ませんでした",mean:"Pasado del verbo (cortés)",exp:"La forma ます en pasado es ました; el pasado negativo es ませんでした.",ej:"映画を見ました。",ejr:"えいがを みました",ejt:"Vi una película.",err:"Usar でした con verbos en vez de ました.",lvl:"N5"},
 {pat:"〜ています",mean:"Acción en curso o estado",exp:"La forma て + います indica acción en progreso (食べています = está comiendo) o estado (結婚しています = está casado).",ej:"今、勉強しています。",ejr:"いま、べんきょうしています",ejt:"Ahora estoy estudiando.",err:"Olvidar que también expresa estados, no solo acción en marcha.",lvl:"N5"},
 {pat:"や",mean:"Y (lista incompleta)",exp:"や une sustantivos en una lista de ejemplos, dando a entender que hay más (a diferencia de と).",ej:"机の上に本やペンがあります。",ejr:"つくえの うえに ほんや ペンが あります",ejt:"Sobre la mesa hay libros, bolígrafos, etc.",err:"Usar や cuando la lista es completa; ahí va と.",lvl:"N5"},
 {pat:"ね",mean:"¿Verdad? (busca acuerdo)",exp:"ね al final pide confirmación o acuerdo del oyente.",ej:"今日は暑いですね。",ejr:"きょうは あついですね",ejt:"Hoy hace calor, ¿verdad?",err:"Confundir ね (acuerdo) con よ (informar).",lvl:"N5"},
 {pat:"よ",mean:"¡Te informo! (énfasis)",exp:"よ al final da información nueva o enfatiza algo que el oyente quizá no sabe.",ej:"その店は休みですよ。",ejr:"その みせは やすみですよ",ejt:"Esa tienda está cerrada (te aviso).",err:"Abusar de よ; puede sonar insistente.",lvl:"N5"},
 {pat:"〜が (pero)",mean:"Pero (conjunción)",exp:"が entre dos frases significa pero: 高いですが、おいしいです = es caro, pero está rico.",ej:"日本語は難しいですが、面白いです。",ejr:"にほんごは むずかしいですが、おもしろいです",ejt:"El japonés es difícil, pero interesante.",err:"Confundir este が con la partícula de sujeto が.",lvl:"N5"},
 {pat:"〜から (porque)",mean:"Porque (razón)",exp:"から tras una frase da la razón: 寒いから、コートを着ます = como hace frío, me pongo abrigo.",ej:"時間がないから、行きません。",ejr:"じかんが ないから、いきません",ejt:"No voy porque no tengo tiempo.",err:"Colocar から antes de la razón en vez de después.",lvl:"N5"},
 {pat:"まだ〜ていません",mean:"Todavía no",exp:"まだ + forma ていません indica que algo aún no ha pasado: まだ食べていません = todavía no he comido.",ej:"宿題はまだ終わっていません。",ejr:"しゅくだいは まだ おわっていません",ejt:"Aún no he terminado los deberes.",err:"Responder con まだ〜ません en vez de まだ〜ていません.",lvl:"N5"},
 {pat:"もう〜ました",mean:"Ya (hecho)",exp:"もう + verbo en pasado indica que algo ya ocurrió: もう食べました = ya he comido.",ej:"もう昼ご飯を食べました。",ejr:"もう ひるごはんを たべました",ejt:"Ya he almorzado.",err:"Confundir もう (ya) con まだ (todavía).",lvl:"N5"},
 {pat:"一番",mean:"El más ~ (superlativo)",exp:"一番 antes de un adjetivo significa el más: 一番大きい = el más grande.",ej:"富士山は日本で一番高い山です。",ejr:"ふじさんは にほんで いちばん たかい やまです",ejt:"El Fuji es la montaña más alta de Japón.",err:"Olvidar で para marcar el grupo de comparación.",lvl:"N5"},
 {pat:"〜より〜のほうが",mean:"~ es más ~ que ~",exp:"A より B のほうが [adj] です = B es más [adj] que A. より marca el punto de comparación.",ej:"バスより電車のほうが速いです。",ejr:"バスより でんしゃの ほうが はやいです",ejt:"El tren es más rápido que el autobús.",err:"Invertir el orden de より y のほうが.",lvl:"N5"},
 {pat:"〜をください",mean:"Deme ~, por favor",exp:"Sustantivo + をください pide algo educadamente: これをください = deme esto, por favor.",ej:"水をください。",ejr:"みずを ください",ejt:"Agua, por favor.",err:"Usarlo con verbos; para verbos va 〜てください.",lvl:"N5"},
 {pat:"〜になる",mean:"Volverse / llegar a ser",exp:"Sustantivo o adjetivo な + になる indica cambio: 先生になる = hacerse profesor; 元気になる = ponerse bien.",ej:"医者になりたいです。",ejr:"いしゃに なりたいです",ejt:"Quiero ser médico.",err:"Con adjetivos い se usa くなる, no になる (大きくなる).",lvl:"N5"},
 {pat:"どんな",mean:"Qué tipo de ~",exp:"どんな + sustantivo pregunta por la clase o características: どんな音楽 = qué tipo de música.",ej:"どんな映画が好きですか。",ejr:"どんな えいがが すきですか",ejt:"¿Qué tipo de películas te gustan?",err:"Confundir どんな (qué tipo) con どう (cómo).",lvl:"N5"},
 {pat:"〜ましょうか",mean:"¿Hago ~? / ¿Hacemos ~?",exp:"ましょうか ofrece ayuda o propone algo: 手伝いましょうか = ¿te ayudo?",ej:"窓を開けましょうか。",ejr:"まどを あけましょうか",ejt:"¿Abro la ventana?",err:"Confundirlo con ましょう (afirmación de hacer juntos).",lvl:"N5"},
 {pat:"これ・それ・あれ",mean:"Esto / eso / aquello",exp:"これ=cerca de mí, それ=cerca de ti, あれ=lejos de ambos. Son pronombres y van solos.",ej:"これは本です。",ejr:"これは ほんです",ejt:"Esto es un libro.",err:"Usar これ delante de un sustantivo; ahí va この.",lvl:"N5"},
 {pat:"この・その・あの",mean:"Este / ese / aquel (+ nombre)",exp:"この/その/あの acompañan siempre a un sustantivo: この本 = este libro.",ej:"その本は私のです。",ejr:"そのほんは わたしのです",ejt:"Ese libro es mío.",err:"Decir これ本 en vez de この本.",lvl:"N5"},
 {pat:"ここ・そこ・あそこ",mean:"Aquí / ahí / allí",exp:"Indican lugar: ここ (donde estoy), そこ (donde estás), あそこ (lejos de ambos).",ej:"トイレはあそこです。",ejr:"トイレは あそこです",ejt:"El baño está allí.",err:"Confundirlos con これ系 (cosas).",lvl:"N5"},
 {pat:"疑問詞 (なに・だれ・どこ・いつ)",mean:"Palabras interrogativas",exp:"なに=qué, だれ=quién, どこ=dónde, いつ=cuándo. Van donde iría la respuesta.",ej:"だれが来ますか。",ejr:"だれが きますか",ejt:"¿Quién viene?",err:"Poner は tras だれ; se usa が (だれが).",lvl:"N5"},
 {pat:"いくら",mean:"Cuánto (precio)",exp:"いくら pregunta el precio de algo.",ej:"これはいくらですか。",ejr:"これは いくらですか",ejt:"¿Cuánto cuesta esto?",err:"Confundir いくら (precio) con いくつ (cantidad/edad).",lvl:"N5"},
 {pat:"どう",mean:"Cómo · qué tal",exp:"どう pregunta por el estado o la impresión de algo.",ej:"日本はどうですか。",ejr:"にほんは どうですか",ejt:"¿Qué tal Japón?",err:"Confundir どう (cómo está) con どんな (qué tipo).",lvl:"N5"},
 {pat:"どうして",mean:"Por qué",exp:"どうして (o なぜ) pregunta la razón; se responde con 〜から.",ej:"どうして来ませんでしたか。",ejr:"どうして きませんでしたか",ejt:"¿Por qué no viniste?",err:"Olvidar responder con から al dar la razón.",lvl:"N5"},
 {pat:"疑問詞＋か",mean:"algo / alguien / algún sitio",exp:"なに＋か=algo, だれ＋か=alguien, どこ＋か=algún sitio.",ej:"何か飲みますか。",ejr:"なにか のみますか",ejt:"¿Bebes algo?",err:"Confundir なにか (algo) con なにも〜ない (nada).",lvl:"N5"},
 {pat:"〜ませんか",mean:"¿No quieres ~? (invitación)",exp:"La forma ません con tono de pregunta invita amablemente.",ej:"一緒に映画を見ませんか。",ejr:"いっしょに えいがを みませんか",ejt:"¿Vemos una peli juntos?",err:"Entenderlo como negación en vez de invitación.",lvl:"N5"},
 {pat:"〜ないでください",mean:"Por favor, no hagas ~",exp:"Forma ない + でください pide no hacer algo.",ej:"ここで写真を撮らないでください。",ejr:"ここで しゃしんを とらないでください",ejt:"No hagas fotos aquí, por favor.",err:"Confundirla con 〜てください (sí hacer).",lvl:"N5"},
 {pat:"〜てもいいです",mean:"Se puede (permiso)",exp:"Forma て + もいいです da o pide permiso.",ej:"入ってもいいですか。",ejr:"はいっても いいですか",ejt:"¿Puedo entrar?",err:"Olvidar la partícula も.",lvl:"N5"},
 {pat:"〜てはいけません",mean:"No se puede (prohibición)",exp:"Forma て + はいけません prohíbe algo.",ej:"ここで遊んではいけません。",ejr:"ここで あそんでは いけません",ejt:"No se puede jugar aquí.",err:"Confundirla con 〜なくてもいい (no hace falta).",lvl:"N5"},
 {pat:"〜かったです",mean:"Pasado de adjetivo い",exp:"Los adjetivos い hacen el pasado cambiando い por かった: 楽しい→楽しかった.",ej:"旅行は楽しかったです。",ejr:"りょこうは たのしかったです",ejt:"El viaje fue divertido.",err:"Decir 楽しいでした (incorrecto).",lvl:"N5"},
 {pat:"〜くなかったです",mean:"Pasado negativo de adjetivo い",exp:"Negativo pasado de adjetivos い: い→くなかった (o くありませんでした).",ej:"試験は難しくなかったです。",ejr:"しけんは むずかしくなかったです",ejt:"El examen no fue difícil.",err:"Decir 難しいじゃなかった (eso es para な-adj y sustantivos).",lvl:"N5"},
 {pat:"〜くて / 〜で (unir adj.)",mean:"Unir adjetivos (y)",exp:"Adjetivos い: い→くて; adjetivos な y sustantivos: +で. 安くておいしい / きれいで静か.",ej:"この店は安くておいしいです。",ejr:"このみせは やすくて おいしいです",ejt:"Esta tienda es barata y rica.",err:"Usar と para unir adjetivos (と es para sustantivos).",lvl:"N5"},
 {pat:"〜くなる",mean:"Volverse ~ (adjetivo い)",exp:"Adjetivo い: い→くなる indica un cambio. 大きくなる = hacerse grande.",ej:"寒くなりました。",ejr:"さむく なりました",ejt:"Se ha puesto frío.",err:"Usar になる con adjetivos い (eso es para な-adj y sustantivos).",lvl:"N5"},
 {pat:"〜くする / にする",mean:"Hacer que algo sea ~",exp:"Adjetivo い→くする; な-adj o sustantivo→にする. Cambiar algo a propósito.",ej:"音を小さくしてください。",ejr:"おとを ちいさく してください",ejt:"Baja el volumen, por favor.",err:"Confundir 〜する (hacer que sea) con 〜なる (volverse solo).",lvl:"N5"},
 {pat:"〜がほしいです",mean:"Querer (algo)",exp:"Sustantivo + がほしい expresa el deseo de tener algo (del hablante).",ej:"新しい車がほしいです。",ejr:"あたらしい くるまが ほしいです",ejt:"Quiero un coche nuevo.",err:"Usarlo para deseos de otras personas.",lvl:"N5"},
 {pat:"ますstem＋に行く",mean:"Ir a hacer ~ (propósito)",exp:"Raíz de la forma ます + に + 行く/来る/帰る indica el propósito del movimiento. 食べに行く = ir a comer.",ej:"映画を見に行きます。",ejr:"えいがを みに いきます",ejt:"Voy a ver una película.",err:"Olvidar la partícula に de propósito.",lvl:"N5"},
 {pat:"〜ごろ",mean:"Alrededor de (un momento)",exp:"ごろ se añade a una hora o momento aproximado. 3時ごろ = sobre las 3.",ej:"7時ごろ起きます。",ejr:"しちじごろ おきます",ejt:"Me levanto sobre las 7.",err:"Usar ごろ con cantidades; ahí va ぐらい.",lvl:"N5"},
 {pat:"〜ぐらい / くらい",mean:"Aproximadamente (cantidad)",exp:"ぐらい (o くらい) indica cantidad o duración aproximada. 千円ぐらい.",ej:"1時間ぐらい勉強します。",ejr:"いちじかんぐらい べんきょうします",ejt:"Estudio una hora más o menos.",err:"Usar ぐらい para una hora concreta; ahí va ごろ.",lvl:"N5"},
 {pat:"〜だけ",mean:"Solo · solamente",exp:"だけ limita: solo eso, nada más. 水だけ飲みます.",ej:"一人だけ来ました。",ejr:"ひとりだけ きました",ejt:"Vino solo una persona.",err:"Confundir だけ con しか (que pide verbo negativo).",lvl:"N5"},
 {pat:"〜しか〜ない",mean:"Solo (con verbo negativo)",exp:"しか + verbo en negativo = solo / nada más, con matiz de poco. 千円しかない.",ej:"水しか飲みません。",ejr:"みずしか のみません",ejt:"Solo bebo agua.",err:"Olvidar poner el verbo en negativo con しか.",lvl:"N5"},
 {pat:"〜つ (contador)",mean:"Contador genérico (1-10)",exp:"ひとつ、ふたつ、みっつ... cuenta cosas generales hasta diez.",ej:"りんごを三つ買います。",ejr:"りんごを みっつ かいます",ejt:"Compro tres manzanas.",err:"Usar este contador para personas; ahí va 〜人.",lvl:"N5"},
 {pat:"〜人 (にん)",mean:"Contador de personas",exp:"Cuenta personas: 一人(ひとり), 二人(ふたり), 三人(さんにん)...",ej:"学生が五人います。",ejr:"がくせいが ごにん います",ejt:"Hay cinco estudiantes.",err:"Decir いちにん/ににん (son ひとり/ふたり).",lvl:"N5"},
 {pat:"〜枚 (まい)",mean:"Contador de cosas planas",exp:"Cuenta objetos finos y planos: papel, sellos, camisetas, platos.",ej:"切符を二枚ください。",ejr:"きっぷを にまい ください",ejt:"Dos billetes, por favor.",err:"Usar 枚 con objetos no planos.",lvl:"N5"},
 {pat:"〜本 (ほん)",mean:"Contador de cosas alargadas",exp:"Cuenta objetos largos y finos. La lectura cambia: 一本(いっぽん), 三本(さんぼん).",ej:"ペンが三本あります。",ejr:"ペンが さんぼん あります",ejt:"Hay tres bolígrafos.",err:"Leer siempre ほん (cambia a ぽん/ぼん según el número).",lvl:"N5"},
 {pat:"〜回 (かい)",mean:"Veces (frecuencia)",exp:"回 cuenta el número de veces. 一回, 二回, 三回.",ej:"一日に三回食べます。",ejr:"いちにちに さんかい たべます",ejt:"Como tres veces al día.",err:"Confundir 回 (veces) con 階 (pisos).",lvl:"N5"},
 {pat:"〜に〜回",mean:"X veces por (periodo)",exp:"[periodo]に[número]回 indica frecuencia. 週に二回 = dos veces por semana.",ej:"週に二回泳ぎます。",ejr:"しゅうに にかい およぎます",ejt:"Nado dos veces por semana.",err:"Invertir el orden; el periodo va primero con に.",lvl:"N5"},
 {pat:"上・下・中 (posición)",mean:"Encima, debajo, dentro...",exp:"Sustantivo + の + 上/下/中/前/後ろ/となり indica posición. 机の上 = encima de la mesa.",ej:"かばんは机の下にあります。",ejr:"かばんは つくえの したに あります",ejt:"El bolso está debajo de la mesa.",err:"Olvidar la partícula の entre el nombre y la posición.",lvl:"N5"},
 {pat:"〜と〜と、どちらが",mean:"¿Cuál de los dos ~?",exp:"AとBと、どちらが [adj] ですか compara dos cosas. La respuesta usa のほうが.",ej:"犬と猫と、どちらが好きですか。",ejr:"いぬと ねこと、どちらが すきですか",ejt:"¿Qué te gusta más, perros o gatos?",err:"Usar どれ (entre 3 o más) cuando solo hay dos; ahí va どちら.",lvl:"N5"},
 {pat:"あまり〜ません",mean:"No mucho ~",exp:"あまり + verbo o adjetivo en negativo = no mucho, no demasiado.",ej:"あまり食べません。",ejr:"あまり たべません",ejt:"No como mucho.",err:"Usar あまり con frase afirmativa.",lvl:"N5"},
 {pat:"ぜんぜん〜ません",mean:"Para nada ~",exp:"ぜんぜん + negativo = en absoluto, nada de nada.",ej:"お酒はぜんぜん飲みません。",ejr:"おさけは ぜんぜん のみません",ejt:"No bebo nada de alcohol.",err:"Usar ぜんぜん con frase afirmativa (en lengua estándar).",lvl:"N5"},
 {pat:"〜でも",mean:"~ o algo así (sugerencia)",exp:"Sustantivo + でも propone algo sin concretar. お茶でも飲みませんか.",ej:"コーヒーでもどうですか。",ejr:"コーヒーでも どうですか",ejt:"¿Te apetece un café o algo?",err:"Confundir este でも con el でも de aunque.",lvl:"N5"},
 {pat:"〜は〜が (dos partículas)",mean:"Tema (は) + lo que se siente (が)",exp:"Con 好き・上手・ほしい etc., el tema lleva は y lo que gusta o se quiere lleva が.",ej:"私は犬が好きです。",ejr:"わたしは いぬが すきです",ejt:"A mí me gustan los perros.",err:"Marcar lo que gusta con は en vez de が.",lvl:"N5"},
 {pat:"〜の (nominalizar)",mean:"Convertir un verbo en nombre",exp:"Verbo en forma simple + の lo convierte en sustantivo: 見るのが好き = me gusta ver.",ej:"本を読むのが好きです。",ejr:"ほんを よむのが すきです",ejt:"Me gusta leer libros.",err:"Olvidar の y unir el verbo directamente a が.",lvl:"N5"},

 /* ===== N4 ===== */
 {pat:"〜て (unir acciones)",mean:"Forma て: enlazar acciones",exp:"La forma て enlaza acciones en orden: 起きて、顔を洗って、出かけます = me levanto, me lavo la cara y salgo.",ej:"朝起きて、コーヒーを飲みます。",ejr:"あさ おきて、コーヒーを のみます",ejt:"Me levanto y bebo café.",err:"Errores al formar la て según el grupo del verbo.",lvl:"N4"},
 {pat:"〜なければなりません",mean:"Hay que / es obligatorio",exp:"Base ない (sin い) + ければなりません: 行かなければなりません = tengo que ir. Coloquial: なきゃ.",ej:"明日までに出さなければなりません。",ejr:"あしたまでに ださなければ なりません",ejt:"Hay que entregarlo para mañana.",err:"Formar mal la base negativa del verbo.",lvl:"N4"},
 {pat:"〜なくてもいいです",mean:"No hace falta",exp:"Base ない → なくてもいいです: 来なくてもいいです = no hace falta que vengas.",ej:"今日は来なくてもいいです。",ejr:"きょうは こなくても いいです",ejt:"Hoy no hace falta que vengas.",err:"Confundirlo con 〜てはいけません (prohibición).",lvl:"N4"},
 {pat:"〜たことがあります",mean:"Haber hecho alguna vez",exp:"Verbo en た + ことがあります expresa experiencia: 日本へ行ったことがあります = he estado en Japón.",ej:"すしを食べたことがあります。",ejr:"すしを たべた ことが あります",ejt:"He comido sushi alguna vez.",err:"Usar la forma presente en vez de la た.",lvl:"N4"},
 {pat:"〜たり〜たりする",mean:"Hacer cosas como ~ y ~",exp:"Verbos en た + り... enumeran actividades como ejemplos: 読んだり書いたりします.",ej:"週末は掃除したり買い物したりします。",ejr:"しゅうまつは そうじしたり かいものしたり します",ejt:"Los findes limpio, hago la compra, etc.",err:"Olvidar el する al final.",lvl:"N4"},
 {pat:"〜ながら",mean:"Mientras (a la vez)",exp:"Raíz de la forma ます + ながら: dos acciones simultáneas del mismo sujeto. 聞きながら勉強する.",ej:"テレビを見ながらご飯を食べます。",ejr:"テレビを みながら ごはんを たべます",ejt:"Como mientras veo la tele.",err:"Usarlo con sujetos distintos para cada acción.",lvl:"N4"},
 {pat:"〜まえに",mean:"Antes de ~",exp:"Verbo en forma diccionario + まえに, o sustantivo + のまえに: 寝るまえに = antes de dormir.",ej:"食べる前に手を洗います。",ejr:"たべる まえに てを あらいます",ejt:"Me lavo las manos antes de comer.",err:"Usar la forma pasada del verbo antes de まえに.",lvl:"N4"},
 {pat:"〜あとで",mean:"Después de ~",exp:"Verbo en た + あとで, o sustantivo + のあとで: 食べたあとで = después de comer.",ej:"仕事のあとで映画を見ます。",ejr:"しごとの あとで えいがを みます",ejt:"Después del trabajo veo una película.",err:"Usar la forma diccionario antes de あとで.",lvl:"N4"},
 {pat:"〜とき",mean:"Cuando ~",exp:"Frase + とき sitúa el momento: 子供のとき = cuando era niño; el tiempo del verbo (行くとき / 行ったとき) cambia el matiz.",ej:"日本へ行ったとき、写真を撮りました。",ejr:"にほんへ いったとき、しゃしんを とりました",ejt:"Cuando fui a Japón, hice fotos.",err:"Ignorar que 行くとき y 行ったとき indican momentos distintos.",lvl:"N4"},
 {pat:"〜と (natural)",mean:"Si / cuando (resultado natural)",exp:"Forma diccionario + と da una consecuencia automática: 押すと、開きます = si lo pulsas, se abre.",ej:"春になると、桜が咲きます。",ejr:"はるに なると、さくらが さきます",ejt:"Cuando llega la primavera, florecen los cerezos.",err:"Usar と con peticiones o voluntad (no se puede).",lvl:"N4"},
 {pat:"〜ば",mean:"Si ~ (condición)",exp:"Forma condicional ば plantea una condición: 安ければ買います = si es barato, lo compro.",ej:"時間があれば、行きます。",ejr:"じかんが あれば、いきます",ejt:"Si tengo tiempo, voy.",err:"Errores al formar la base ば del verbo o adjetivo.",lvl:"N4"},
 {pat:"〜たら",mean:"Si / cuando (luego)",exp:"Forma た + ら es el condicional más versátil: 雨が降ったら、行きません.",ej:"駅に着いたら、電話してください。",ejr:"えきに ついたら、でんわして ください",ejt:"Cuando llegues a la estación, llama.",err:"Olvidar que たら sirve tanto para si como para cuando.",lvl:"N4"},
 {pat:"〜なら",mean:"Si (es el caso de) ~",exp:"なら retoma un tema y da una respuesta condicional: 日本へ行くなら、京都がいいです.",ej:"安いなら、買います。",ejr:"やすいなら、かいます",ejt:"Si es barato, lo compro.",err:"Confundir なら con たら/ば; なら parte de lo que dijo el otro.",lvl:"N4"},
 {pat:"〜つもりです",mean:"Tener la intención de ~",exp:"Forma diccionario + つもりです expresa un plan firme: 行くつもりです = pienso ir.",ej:"来年、日本へ行くつもりです。",ejr:"らいねん、にほんへ いく つもりです",ejt:"El año que viene pienso ir a Japón.",err:"Usar la forma ます antes de つもり (va la forma diccionario).",lvl:"N4"},
 {pat:"〜ようと思います",mean:"Pensar hacer ~",exp:"Forma volitiva (よう/おう) + と思います: decisión reciente. 行こうと思います = creo que iré.",ej:"日本語を勉強しようと思います。",ejr:"にほんごを べんきょうしようと おもいます",ejt:"Pienso estudiar japonés.",err:"Errores al formar la base volitiva.",lvl:"N4"},
 {pat:"〜でしょう",mean:"Probablemente / supongo",exp:"でしょう (informal だろう) expresa probabilidad o pide acuerdo: 明日は雨でしょう.",ej:"明日は晴れるでしょう。",ejr:"あしたは はれるでしょう",ejt:"Mañana probablemente haga sol.",err:"Usar でしょう como futuro totalmente seguro.",lvl:"N4"},
 {pat:"〜かもしれません",mean:"Quizá / puede que ~",exp:"かもしれません expresa posibilidad, menos segura que でしょう: 雨が降るかもしれません.",ej:"彼は来ないかもしれません。",ejr:"かれは こない かもしれません",ejt:"Puede que él no venga.",err:"Confundir su grado de certeza con でしょう.",lvl:"N4"},
 {pat:"〜はずです",mean:"Se supone que / debería",exp:"はずです indica una expectativa lógica: 彼は来るはずです = se supone que vendrá.",ej:"電車は3時に着くはずです。",ejr:"でんしゃは さんじに つく はずです",ejt:"El tren debería llegar a las 3.",err:"Confundirlo con べき (deber moral).",lvl:"N4"},
 {pat:"〜んです",mean:"Es que ~ (explicación)",exp:"んです (informal んだ) da explicación o contexto: 頭が痛いんです = es que me duele la cabeza.",ej:"どうして遅れたんですか。",ejr:"どうして おくれたんですか",ejt:"¿Por qué te has retrasado?",err:"Abusar de んです en frases neutras sin matiz explicativo.",lvl:"N4"},
 {pat:"〜ても",mean:"Aunque / aun si ~",exp:"Forma て + も concede: 雨が降っても行きます = aunque llueva, voy.",ej:"高くても買います。",ejr:"たかくても かいます",ejt:"Aunque sea caro, lo compro.",err:"Confundir 〜ても con 〜てもいい (permiso).",lvl:"N4"},
 {pat:"〜のに",mean:"A pesar de que ~",exp:"のに une dos frases con un contraste inesperado y cierto reproche: 勉強したのに、落ちた.",ej:"薬を飲んだのに、まだ痛いです。",ejr:"くすりを のんだのに、まだ いたいです",ejt:"Aunque tomé la medicina, aún me duele.",err:"Confundir のに con ので (causa).",lvl:"N4"},
 {pat:"〜ので",mean:"Como / porque (educado)",exp:"ので da una razón de forma más suave y educada que から: 用事があるので、帰ります.",ej:"熱があるので、休みます。",ejr:"ねつが あるので、やすみます",ejt:"Como tengo fiebre, descanso.",err:"Tras adjetivos な o sustantivos va なので, no ので.",lvl:"N4"},
 {pat:"〜ことができる",mean:"Poder / ser capaz de ~",exp:"Forma diccionario + ことができる expresa capacidad: 泳ぐことができます = sé nadar.",ej:"日本語を話すことができます。",ejr:"にほんごを はなす ことが できます",ejt:"Sé hablar japonés.",err:"Mezclarlo con la forma potencial sin coherencia.",lvl:"N4"},
 {pat:"〜られる (potencial)",mean:"Forma potencial (poder hacer)",exp:"Potencial: 食べる→食べられる, 飲む→飲める, する→できる. Lo que se puede hacer suele ir con が.",ej:"漢字が読めます。",ejr:"かんじが よめます",ejt:"Puedo leer kanji.",err:"Usar を en vez de が con el potencial.",lvl:"N4"},
 {pat:"〜よう (volitivo)",mean:"Vamos / voy a (informal)",exp:"Volitiva informal (行こう, 食べよう, しよう): propone o decide, versión coloquial de ましょう.",ej:"一緒に帰ろう。",ejr:"いっしょに かえろう",ejt:"Volvamos juntos.",err:"Errores al formar la volitiva según el grupo del verbo.",lvl:"N4"},
 {pat:"〜られる (pasiva)",mean:"Voz pasiva",exp:"La pasiva (見られる, 言われる, される): el sujeto recibe la acción. 先生にしかられた = me regañó el profesor.",ej:"みんなに笑われました。",ejr:"みんなに わらわれました",ejt:"Todos se rieron de mí.",err:"Confundir la pasiva con el potencial (igual forma en ru-verbos).",lvl:"N4"},
 {pat:"〜てみる",mean:"Probar a hacer ~",exp:"Forma て + みる: hacer algo para ver qué tal. 食べてみる = probar a comer.",ej:"この服を着てみます。",ejr:"この ふくを きてみます",ejt:"Me pruebo esta ropa.",err:"Tomarlo literalmente como ver.",lvl:"N4"},
 {pat:"〜ておく",mean:"Hacer algo de antemano",exp:"Forma て + おく: preparar con antelación. 予約しておく = reservar. Coloquial: 〜とく.",ej:"飲み物を買っておきます。",ejr:"のみものを かっておきます",ejt:"Compro las bebidas de antemano.",err:"Ignorar el matiz de preparación.",lvl:"N4"},
 {pat:"〜てしまう",mean:"Acabar haciendo / sin querer",exp:"Forma て + しまう: completar algo o hacerlo sin querer (con pena). Coloquial: 〜ちゃう.",ej:"宿題を忘れてしまいました。",ejr:"しゅくだいを わすれて しまいました",ejt:"Se me olvidaron los deberes.",err:"Pasar por alto el matiz de arrepentimiento.",lvl:"N4"},
 {pat:"〜そうです (apariencia)",mean:"Parece que ~ (por lo que veo)",exp:"Raíz de adjetivo/verbo + そうです: impresión visual. おいしそうです = tiene buena pinta.",ej:"雨が降りそうです。",ejr:"あめが ふりそうです",ejt:"Parece que va a llover.",err:"Confundirlo con そうです de rumor.",lvl:"N4"},
 {pat:"〜そうです (rumor)",mean:"Dicen que ~ (información oída)",exp:"Forma normal + そうです transmite algo que oíste: 雨が降るそうです = dicen que va a llover.",ej:"彼は来ないそうです。",ejr:"かれは こない そうです",ejt:"Dicen que él no viene.",err:"Mezclarlo con そうです de apariencia (distinta base).",lvl:"N4"},
 {pat:"〜ようです",mean:"Parece que ~ (deducción)",exp:"ようです expresa una conjetura basada en indicios: 誰かいるようです = parece que hay alguien.",ej:"風邪をひいたようです。",ejr:"かぜを ひいた ようです",ejt:"Parece que me he resfriado.",err:"Confundir el grado de certeza con そう / らしい.",lvl:"N4"},
 {pat:"あげる・くれる・もらう",mean:"Dar y recibir",exp:"あげる (yo doy a otro), くれる (otro me da a mí), もらう (yo recibo). El punto de vista cambia el verbo.",ej:"友だちにプレゼントをあげました。",ejr:"ともだちに プレゼントを あげました",ejt:"Le di un regalo a un amigo.",err:"Usar あげる cuando alguien te da algo (es くれる).",lvl:"N4"},
 {pat:"〜てくれる・てもらう",mean:"Hacer favores",exp:"Forma て + あげる/くれる/もらう: hacer algo por alguien. 手伝ってくれた = me ayudó.",ej:"友だちが手伝ってくれました。",ejr:"ともだちが てつだって くれました",ejt:"Un amigo me ayudó.",err:"Equivocar la dirección del favor (くれる vs あげる).",lvl:"N4"},
 {pat:"〜すぎる",mean:"Demasiado ~",exp:"Raíz de verbo/adjetivo + すぎる: exceso. 食べすぎる = comer demasiado; 高すぎる = demasiado caro.",ej:"昨日は食べすぎました。",ejr:"きのうは たべすぎました",ejt:"Ayer comí demasiado.",err:"Olvidar quitar い/な del adjetivo antes de すぎる.",lvl:"N4"},
 {pat:"〜やすい・〜にくい",mean:"Fácil / difícil de ~",exp:"Raíz de la forma ます + やすい (fácil) o にくい (difícil): 読みやすい = fácil de leer.",ej:"このペンは書きやすいです。",ejr:"この ペンは かきやすいです",ejt:"Este boli es fácil de usar.",err:"Conjugarlos como verbos en vez de como adjetivos い.",lvl:"N4"},
 {pat:"〜かた",mean:"Manera de hacer ~",exp:"Raíz de la forma ます + 方(かた): forma de hacer algo. 使い方 = modo de uso; 作り方 = receta.",ej:"漢字の書き方を教えてください。",ejr:"かんじの かきかたを おしえて ください",ejt:"Enséñame a escribir kanji.",err:"Olvidar que el objeto pasa a llevar の (本の読み方).",lvl:"N4"},
 {pat:"〜し",mean:"Y además (razones)",exp:"し enumera razones o cualidades que se suman: 安いし、おいしいし、よく行きます.",ej:"この店は安いし、近いです。",ejr:"この みせは やすいし、ちかいです",ejt:"Esta tienda es barata y, además, está cerca.",err:"Usar し donde solo hay un motivo (mejor から).",lvl:"N4"}
]

};
