/* ============================================================
   CONTENIDO de Japanese N1 Path
   Edita SOLO este archivo para anadir o corregir contenido.
   Estructura: window.CONTENT = { kanji:[...], vocab:[...], grammar:[...] }
   ============================================================ */
window.CONTENT = {

/* ---------------- KANJI (N5) ---------------- */
kanji: [
 {c:"木",kun:"き",on:"モク・ボク",say:"き",mean:"Árbol · madera",ej:"木曜日",ejr:"もくようび",ejt:"jueves",tip:"Un tronco vertical con dos ramas que caen.",lvl:"N5"},
 {c:"水",kun:"みず",on:"スイ",say:"みず",mean:"Agua",ej:"水曜日",ejr:"すいようび",ejt:"miércoles",tip:"Una corriente de agua fluyendo.",lvl:"N5"},
 {c:"火",kun:"ひ",on:"カ",say:"ひ",mean:"Fuego",ej:"火曜日",ejr:"かようび",ejt:"martes",tip:"Una figura con chispas saltando: fuego.",lvl:"N5"},
 {c:"山",kun:"やま",on:"サン",say:"やま",mean:"Montaña",ej:"富士山",ejr:"ふじさん",ejt:"monte Fuji",tip:"Tres picos: una montaña.",lvl:"N5"},
 {c:"川",kun:"かわ",on:"セン",say:"かわ",mean:"Río",ej:"川",ejr:"かわ",ejt:"río",tip:"Tres líneas de agua en paralelo.",lvl:"N5"},
 {c:"日",kun:"ひ",on:"ニチ・ジツ",say:"ひ",mean:"Sol · día",ej:"日本",ejr:"にほん",ejt:"Japón",tip:"El sol dentro de un marco.",lvl:"N5"},
 {c:"月",kun:"つき",on:"ゲツ・ガツ",say:"つき",mean:"Luna · mes",ej:"月曜日",ejr:"げつようび",ejt:"lunes",tip:"Una luna creciente.",lvl:"N5"},
 {c:"人",kun:"ひと",on:"ジン・ニン",say:"ひと",mean:"Persona",ej:"日本人",ejr:"にほんじん",ejt:"persona japonesa",tip:"Dos piernas caminando.",lvl:"N5"},
 {c:"大",kun:"おお",on:"ダイ・タイ",say:"おおきい",mean:"Grande",ej:"大学",ejr:"だいがく",ejt:"universidad",tip:"Una persona con los brazos abiertos: grande.",lvl:"N5"},
 {c:"小",kun:"ちい",on:"ショウ",say:"ちいさい",mean:"Pequeño",ej:"小さい",ejr:"ちいさい",ejt:"pequeño",tip:"Algo partido en trocitos diminutos.",lvl:"N5"},
 {c:"口",kun:"くち",on:"コウ",say:"くち",mean:"Boca",ej:"入口",ejr:"いりぐち",ejt:"entrada",tip:"Una boca abierta, cuadrada.",lvl:"N5"},
 {c:"目",kun:"め",on:"モク",say:"め",mean:"Ojo",ej:"目",ejr:"め",ejt:"ojo",tip:"Un ojo puesto de pie.",lvl:"N5"},
 {c:"一",kun:"ひと(つ)",on:"イチ・イツ",say:"いち",mean:"Uno",ej:"一つ",ejr:"ひとつ",ejt:"uno (objeto)",tip:"Una sola línea: el número uno.",lvl:"N5"},
 {c:"二",kun:"ふた(つ)",on:"ニ",say:"に",mean:"Dos",ej:"二つ",ejr:"ふたつ",ejt:"dos (objetos)",tip:"Dos líneas: el número dos.",lvl:"N5"},
 {c:"三",kun:"み(っつ)",on:"サン",say:"さん",mean:"Tres",ej:"三つ",ejr:"みっつ",ejt:"tres (objetos)",tip:"Tres líneas apiladas.",lvl:"N5"},
 {c:"四",kun:"よ(っつ)・よん",on:"シ",say:"よん",mean:"Cuatro",ej:"四つ",ejr:"よっつ",ejt:"cuatro (objetos)",tip:"Una boca con piernas: el cuatro.",lvl:"N5"},
 {c:"五",kun:"いつ(つ)",on:"ゴ",say:"ご",mean:"Cinco",ej:"五つ",ejr:"いつつ",ejt:"cinco (objetos)",tip:"Líneas cruzadas: el cinco.",lvl:"N5"},
 {c:"中",kun:"なか",on:"チュウ",say:"なか",mean:"Centro · dentro",ej:"中国",ejr:"ちゅうごく",ejt:"China",tip:"Una línea que atraviesa el centro de una caja.",lvl:"N5"},
 {c:"本",kun:"もと",on:"ホン",say:"ほん",mean:"Libro · origen",ej:"日本",ejr:"にほん",ejt:"Japón",tip:"Un árbol con una marca en la raíz: el origen.",lvl:"N5"},
 {c:"学",kun:"まな(ぶ)",on:"ガク",say:"がく",mean:"Aprender · estudio",ej:"学生",ejr:"がくせい",ejt:"estudiante",tip:"Un niño bajo un techo, aprendiendo.",lvl:"N5"},
 {c:"生",kun:"い(きる)・なま",on:"セイ・ショウ",say:"せい",mean:"Vida · nacer",ej:"先生",ejr:"せんせい",ejt:"profesor",tip:"Un brote que nace de la tierra.",lvl:"N5"},
 {c:"先",kun:"さき",on:"セン",say:"せん",mean:"Antes · anterior",ej:"先生",ejr:"せんせい",ejt:"profesor",tip:"Una persona que va por delante.",lvl:"N5"},
 {c:"年",kun:"とし",on:"ネン",say:"とし",mean:"Año",ej:"今年",ejr:"ことし",ejt:"este año",tip:"El paso de las cosechas: un año.",lvl:"N5"},
 {c:"円",kun:"まる(い)",on:"エン",say:"えん",mean:"Yen · redondo",ej:"百円",ejr:"ひゃくえん",ejt:"cien yenes",tip:"Una moneda redonda: el yen.",lvl:"N5"}
],

/* ---------------- VOCABULARIO (N5) ---------------- */
vocab: [
 {w:"私",r:"わたし",say:"わたし",mean:"Yo",ej:"私は学生です。",ejr:"わたしは がくせいです",ejt:"Soy estudiante.",lvl:"N5"},
 {w:"学生",r:"がくせい",say:"がくせい",mean:"Estudiante",ej:"彼は学生です。",ejr:"かれは がくせいです",ejt:"Él es estudiante.",lvl:"N5"},
 {w:"先生",r:"せんせい",say:"せんせい",mean:"Profesor / profesora",ej:"先生、こんにちは。",ejr:"せんせい、こんにちは",ejt:"Hola, profesor.",lvl:"N5"},
 {w:"友だち",r:"ともだち",say:"ともだち",mean:"Amigo / amiga",ej:"友だちと話します。",ejr:"ともだちと はなします",ejt:"Hablo con un amigo.",lvl:"N5"},
 {w:"学校",r:"がっこう",say:"がっこう",mean:"Escuela",ej:"学校へ行きます。",ejr:"がっこうへ いきます",ejt:"Voy a la escuela.",lvl:"N5"},
 {w:"日本",r:"にほん",say:"にほん",mean:"Japón",ej:"ここは日本です。",ejr:"ここは にほんです",ejt:"Esto es Japón.",lvl:"N5"},
 {w:"食べる",r:"たべる",say:"たべる",mean:"Comer",ej:"ご飯を食べます。",ejr:"ごはんを たべます",ejt:"Como (arroz).",lvl:"N5"},
 {w:"飲む",r:"のむ",say:"のむ",mean:"Beber",ej:"お茶を飲みます。",ejr:"おちゃを のみます",ejt:"Bebo té.",lvl:"N5"},
 {w:"行く",r:"いく",say:"いく",mean:"Ir",ej:"駅へ行きます。",ejr:"えきへ いきます",ejt:"Voy a la estación.",lvl:"N5"},
 {w:"来る",r:"くる",say:"くる",mean:"Venir",ej:"友だちが来ます。",ejr:"ともだちが きます",ejt:"Viene un amigo.",lvl:"N5"},
 {w:"見る",r:"みる",say:"みる",mean:"Ver · mirar",ej:"テレビを見ます。",ejr:"テレビを みます",ejt:"Veo la tele.",lvl:"N5"},
 {w:"聞く",r:"きく",say:"きく",mean:"Escuchar · preguntar",ej:"音楽を聞きます。",ejr:"おんがくを ききます",ejt:"Escucho música.",lvl:"N5"},
 {w:"話す",r:"はなす",say:"はなす",mean:"Hablar",ej:"日本語を話します。",ejr:"にほんごを はなします",ejt:"Hablo japonés.",lvl:"N5"},
 {w:"読む",r:"よむ",say:"よむ",mean:"Leer",ej:"本を読みます。",ejr:"ほんを よみます",ejt:"Leo un libro.",lvl:"N5"},
 {w:"書く",r:"かく",say:"かく",mean:"Escribir",ej:"手紙を書きます。",ejr:"てがみを かきます",ejt:"Escribo una carta.",lvl:"N5"},
 {w:"大きい",r:"おおきい",say:"おおきい",mean:"Grande",ej:"大きい家です。",ejr:"おおきい いえです",ejt:"Es una casa grande.",lvl:"N5"},
 {w:"小さい",r:"ちいさい",say:"ちいさい",mean:"Pequeño",ej:"小さい犬です。",ejr:"ちいさい いぬです",ejt:"Es un perro pequeño.",lvl:"N5"},
 {w:"水",r:"みず",say:"みず",mean:"Agua",ej:"水を飲みます。",ejr:"みずを のみます",ejt:"Bebo agua.",lvl:"N5"},
 {w:"本",r:"ほん",say:"ほん",mean:"Libro",ej:"本を読みます。",ejr:"ほんを よみます",ejt:"Leo un libro.",lvl:"N5"},
 {w:"今日",r:"きょう",say:"きょう",mean:"Hoy",ej:"今日は寒いです。",ejr:"きょうは さむいです",ejt:"Hoy hace frío.",lvl:"N5"}
],

/* ---------------- GRAMÁTICA ---------------- */
grammar: [
 /* ===== N5 ===== */
 {pat:"〜です",mean:"Ser / estar (cortés)",exp:"です va al final para afirmar de forma educada: A は B です significa A es B. Su forma informal es だ.",ej:"わたしは学生です。",ejr:"わたしは がくせいです",ejt:"Soy estudiante.",err:"En lenguaje cortés no se puede omitir です.",lvl:"N5"},
 {pat:"は",mean:"Partícula de tema (se lee wa)",exp:"は marca el tema: de lo que se habla. Aunque se escribe は, se pronuncia wa.",ej:"これは本です。",ejr:"これは ほんです",ejt:"Esto es un libro.",err:"Pronunciarla ha en vez de wa, o confundirla con が.",lvl:"N5"},
 {pat:"が",mean:"Sujeto / información nueva",exp:"が marca el sujeto, sobre todo cuando presentas información nueva o respondes a quién o qué.",ej:"猫がいます。",ejr:"ねこが います",ejt:"Hay un gato.",err:"Usar は cuando en realidad presentas algo por primera vez.",lvl:"N5"},
 {pat:"を",mean:"Objeto directo (se lee o)",exp:"を marca lo que recibe la acción del verbo. Se escribe を pero se lee o.",ej:"パンを食べます。",ejr:"パンを たべます",ejt:"Como pan.",err:"Escribir お en lugar de を.",lvl:"N5"},
 {pat:"に",mean:"Destino · momento · existencia",exp:"に indica el punto al que se llega, el momento exacto, o el lugar donde algo existe: 7時に, 学校に行く.",ej:"学校に行きます。",ejr:"がっこうに いきます",ejt:"Voy a la escuela.",err:"Confundir に (destino) con で (lugar de acción).",lvl:"N5"},
 {pat:"で",mean:"Lugar de acción · medio",exp:"で indica dónde ocurre una acción o con qué medio se hace: 図書館で勉強する, バスで行く.",ej:"図書館で勉強します。",ejr:"としょかんで べんきょうします",ejt:"Estudio en la biblioteca.",err:"Usar に para el lugar donde realizas una acción.",lvl:"N5"},
 {pat:"へ",mean:"Dirección (se lee e)",exp:"へ indica la dirección hacia la que te mueves. Se escribe へ pero se lee e. Parecido a に de destino.",ej:"東京へ行きます。",ejr:"とうきょうへ いきます",ejt:"Voy hacia Tokio.",err:"Leerla he en vez de e.",lvl:"N5"},
 {pat:"の",mean:"Posesión · unión de nombres",exp:"の une dos sustantivos: el primero describe o posee al segundo. わたしの本 = mi libro.",ej:"わたしの本です。",ejr:"わたしの ほんです",ejt:"Es mi libro.",err:"Olvidar の entre dos sustantivos.",lvl:"N5"},
 {pat:"と",mean:"Y (lista completa) · con",exp:"と une sustantivos en una lista completa (A と B) y también significa con alguien.",ej:"パンとたまごを食べます。",ejr:"パンと たまごを たべます",ejt:"Como pan y huevo.",err:"Usar と para listas incompletas; para esas se usa や.",lvl:"N5"},
 {pat:"も",mean:"También / tampoco",exp:"も sustituye a は o が y significa también. En frases negativas significa tampoco.",ej:"わたしも学生です。",ejr:"わたしも がくせいです",ejt:"Yo también soy estudiante.",err:"Mantener は o が junto con も; も los reemplaza.",lvl:"N5"},
 {pat:"か",mean:"Partícula de pregunta",exp:"か al final convierte la frase en pregunta. En japonés cortés no hace falta signo de interrogación.",ej:"学生ですか。",ejr:"がくせいですか",ejt:"¿Eres estudiante?",err:"Olvidar か y depender solo del tono.",lvl:"N5"},
 {pat:"から〜まで",mean:"Desde ~ hasta ~",exp:"から marca el inicio (desde) y まで el final (hasta), en tiempo o en lugar.",ej:"9時から5時まで働きます。",ejr:"くじから ごじまで はたらきます",ejt:"Trabajo de 9 a 5.",err:"Invertir el orden de las partículas.",lvl:"N5"},
 {pat:"〜ません",mean:"Negativo cortés del verbo",exp:"La forma ます se hace negativa cambiándola por ません: 行きます → 行きません (no voy).",ej:"今日は行きません。",ejr:"きょうは いきません",ejt:"Hoy no voy.",err:"Negar con ない en contexto cortés en vez de ません.",lvl:"N5"},
 {pat:"〜たいです",mean:"Querer (hacer algo)",exp:"Se quita ます del verbo y se añade たいです para expresar el deseo del hablante: 飲みます → 飲みたいです.",ej:"水が飲みたいです。",ejr:"みずが のみたいです",ejt:"Quiero beber agua.",err:"Usarlo para deseos de otras personas; たい es para el hablante.",lvl:"N5"},
 {pat:"〜てください",mean:"Por favor, haz ~",exp:"La forma て del verbo + ください pide algo de forma educada: 見てください = mira, por favor.",ej:"名前を書いてください。",ejr:"なまえを かいてください",ejt:"Escribe tu nombre, por favor.",err:"Equivocarse al formar la forma て del verbo.",lvl:"N5"},
 {pat:"い-adjetivos",mean:"Adjetivos terminados en い",exp:"Modifican directamente al sustantivo (大きい車) y se niegan cambiando い por くない: 大きい → 大きくない.",ej:"これは大きい車です。",ejr:"これは おおきい くるまです",ejt:"Este es un coche grande.",err:"Poner な después de un adjetivo い.",lvl:"N5"},
 {pat:"な-adjetivos",mean:"Adjetivos que necesitan な",exp:"Necesitan な para unirse a un sustantivo (きれいな花) pero NO la usan delante de です (きれいです).",ej:"きれいな花ですね。",ejr:"きれいな はなですね",ejt:"Es una flor bonita, ¿verdad?",err:"Decir きれいなです en vez de きれいです.",lvl:"N5"},
 {pat:"〜ましょう",mean:"Hagamos ~ (invitación)",exp:"Se cambia ます por ましょう para proponer hacer algo juntos: 行きましょう = vamos.",ej:"一緒に行きましょう。",ejr:"いっしょに いきましょう",ejt:"Vamos juntos.",err:"Confundirlo con ましょうか, que ofrece ayuda.",lvl:"N5"},
 {pat:"あります / います",mean:"Existir (cosas / seres vivos)",exp:"あります para cosas y plantas; います para personas y animales. El sujeto va con が.",ej:"本があります。",ejr:"ほんが あります",ejt:"Hay un libro.",err:"Usar あります con personas o animales.",lvl:"N5"},
 {pat:"〜が好きです",mean:"Me gusta ~",exp:"好き es un adjetivo な y lo que gusta se marca con が, no con を: すしが好きです.",ej:"すしが好きです。",ejr:"すしが すきです",ejt:"Me gusta el sushi.",err:"Marcar lo que gusta con を en lugar de が.",lvl:"N5"},
 {pat:"〜でした / ではありません",mean:"Pasado y negativo de です",exp:"です en pasado es でした; en negativo, ではありません (coloquial じゃない). 学生でした = era estudiante.",ej:"きのうは休みでした。",ejr:"きのうは やすみでした",ejt:"Ayer fue día libre.",err:"Combinar です con でした o con じゃない (no se juntan).",lvl:"N5"},
 {pat:"〜ました / ませんでした",mean:"Pasado del verbo (cortés)",exp:"La forma ます en pasado es ました; el pasado negativo es ませんでした.",ej:"映画を見ました。",ejr:"えいがを みました",ejt:"Vi una película.",err:"Usar でした con verbos en vez de ました.",lvl:"N5"},
 {pat:"〜ています",mean:"Acción en curso o estado",exp:"La forma て + います indica acción en progreso (食べています = está comiendo) o estado (結婚しています = está casado).",ej:"今、勉強しています。",ejr:"いま、べんきょうしています",ejt:"Ahora estoy estudiando.",err:"Olvidar que también expresa estados, no solo acción en marcha.",lvl:"N5"},
 {pat:"や",mean:"Y (lista incompleta)",exp:"や une sustantivos en una lista de ejemplos, dando a entender que hay más (a diferencia de と).",ej:"机の上に本やペンがあります。",ejr:"つくえの うえに ほんや ペンが あります",ejt:"Sobre la mesa hay libros, bolígrafos, etc.",err:"Usar や cuando la lista es completa; ahí va と.",lvl:"N5"},
 {pat:"ね",mean:"¿Verdad? (busca acuerdo)",exp:"ね al final pide confirmación o acuerdo del oyente.",ej:"今日は暑いですね。",ejr:"きょうは あついですね",ejt:"Hoy hace calor, ¿verdad?",err:"Confundir ね (acuerdo) con よ (informar).",lvl:"N5"},
 {pat:"よ",mean:"¡Te informo! (énfasis)",exp:"よ al final da información nueva o enfatiza algo que el oyente quizá no sabe.",ej:"その店は休みですよ。",ejr:"その みせは やすみですよ",ejt:"Esa tienda está cerrada (te aviso).",err:"Abusar de よ; puede sonar insistente.",lvl:"N5"},
 {pat:"〜が (pero)",mean:"Pero (conjunción)",exp:"が entre dos frases significa pero: 高いですが、おいしいです = es caro, pero está rico.",ej:"日本語は難しいですが、面白いです。",ejr:"にほんごは むずかしいですが、おもしろいです",ejt:"El japonés es difícil, pero interesante.",err:"Confundir este が con la partícula de sujeto が.",lvl:"N5"},
 {pat:"〜から (porque)",mean:"Porque (razón)",exp:"から tras una frase da la razón: 寒いから、コートを着ます = como hace frío, me pongo abrigo.",ej:"時間がないから、行きません。",ejr:"じかんが ないから、いきません",ejt:"No voy porque no tengo tiempo.",err:"Colocar から antes de la razón en vez de después.",lvl:"N5"},
 {pat:"まだ〜ていません",mean:"Todavía no",exp:"まだ + forma ていません indica que algo aún no ha pasado: まだ食べていません = todavía no he comido.",ej:"宿題はまだ終わっていません。",ejr:"しゅくだいは まだ おわっていません",ejt:"Aún no he terminado los deberes.",err:"Responder con まだ〜ません en vez de まだ〜ていません.",lvl:"N5"},
 {pat:"もう〜ました",mean:"Ya (hecho)",exp:"もう + verbo en pasado indica que algo ya ocurrió: もう食べました = ya he comido.",ej:"もう昼ご飯を食べました。",ejr:"もう ひるごはんを たべました",ejt:"Ya he almorzado.",err:"Confundir もう (ya) con まだ (todavía).",lvl:"N5"},
 {pat:"一番",mean:"El más ~ (superlativo)",exp:"一番 antes de un adjetivo significa el más: 一番大きい = el más grande.",ej:"富士山は日本で一番高い山です。",ejr:"ふじさんは にほんで いちばん たかい やまです",ejt:"El Fuji es la montaña más alta de Japón.",err:"Olvidar で para marcar el grupo de comparación.",lvl:"N5"},
 {pat:"〜より〜のほうが",mean:"~ es más ~ que ~",exp:"A より B のほうが [adj] です = B es más [adj] que A. より marca el punto de comparación.",ej:"バスより電車のほうが速いです。",ejr:"バスより でんしゃの ほうが はやいです",ejt:"El tren es más rápido que el autobús.",err:"Invertir el orden de より y のほうが.",lvl:"N5"},
 {pat:"〜をください",mean:"Deme ~, por favor",exp:"Sustantivo + をください pide algo educadamente: これをください = deme esto, por favor.",ej:"水をください。",ejr:"みずを ください",ejt:"Agua, por favor.",err:"Usarlo con verbos; para verbos va 〜てください.",lvl:"N5"},
 {pat:"〜になる",mean:"Volverse / llegar a ser",exp:"Sustantivo o adjetivo な + になる indica cambio: 先生になる = hacerse profesor; 元気になる = ponerse bien.",ej:"医者になりたいです。",ejr:"いしゃに なりたいです",ejt:"Quiero ser médico.",err:"Con adjetivos い se usa くなる, no になる (大きくなる).",lvl:"N5"},
 {pat:"どんな",mean:"Qué tipo de ~",exp:"どんな + sustantivo pregunta por la clase o características: どんな音楽 = qué tipo de música.",ej:"どんな映画が好きですか。",ejr:"どんな えいがが すきですか",ejt:"¿Qué tipo de películas te gustan?",err:"Confundir どんな (qué tipo) con どう (cómo).",lvl:"N5"},
 {pat:"〜ましょうか",mean:"¿Hago ~? / ¿Hacemos ~?",exp:"ましょうか ofrece ayuda o propone algo: 手伝いましょうか = ¿te ayudo?",ej:"窓を開けましょうか。",ejr:"まどを あけましょうか",ejt:"¿Abro la ventana?",err:"Confundirlo con ましょう (afirmación de hacer juntos).",lvl:"N5"},

 /* ===== N4 ===== */
 {pat:"〜て (unir acciones)",mean:"Forma て: enlazar acciones",exp:"La forma て enlaza acciones en orden: 起きて、顔を洗って、出かけます = me levanto, me lavo la cara y salgo.",ej:"朝起きて、コーヒーを飲みます。",ejr:"あさ おきて、コーヒーを のみます",ejt:"Me levanto y bebo café.",err:"Errores al formar la て según el grupo del verbo.",lvl:"N4"},
 {pat:"〜てもいいです",mean:"Se puede / está permitido",exp:"Forma て + もいいです da permiso: 入ってもいいです = puedes entrar.",ej:"ここで写真を撮ってもいいですか。",ejr:"ここで しゃしんを とっても いいですか",ejt:"¿Puedo hacer fotos aquí?",err:"Olvidar la forma て antes de もいい.",lvl:"N4"},
 {pat:"〜てはいけません",mean:"No se puede / prohibido",exp:"Forma て + はいけません prohíbe: 遊んではいけません = no se puede jugar.",ej:"ここでたばこを吸ってはいけません。",ejr:"ここで たばこを すっては いけません",ejt:"No se puede fumar aquí.",err:"Confundirlo con 〜なくてもいい (no es necesario).",lvl:"N4"},
 {pat:"〜なければなりません",mean:"Hay que / es obligatorio",exp:"Base ない (sin い) + ければなりません: 行かなければなりません = tengo que ir. Coloquial: なきゃ.",ej:"明日までに出さなければなりません。",ejr:"あしたまでに ださなければ なりません",ejt:"Hay que entregarlo para mañana.",err:"Formar mal la base negativa del verbo.",lvl:"N4"},
 {pat:"〜なくてもいいです",mean:"No hace falta",exp:"Base ない → なくてもいいです: 来なくてもいいです = no hace falta que vengas.",ej:"今日は来なくてもいいです。",ejr:"きょうは こなくても いいです",ejt:"Hoy no hace falta que vengas.",err:"Confundirlo con 〜てはいけません (prohibición).",lvl:"N4"},
 {pat:"〜たことがあります",mean:"Haber hecho alguna vez",exp:"Verbo en た + ことがあります expresa experiencia: 日本へ行ったことがあります = he estado en Japón.",ej:"すしを食べたことがあります。",ejr:"すしを たべた ことが あります",ejt:"He comido sushi alguna vez.",err:"Usar la forma presente en vez de la た.",lvl:"N4"},
 {pat:"〜たり〜たりする",mean:"Hacer cosas como ~ y ~",exp:"Verbos en た + り... enumeran actividades como ejemplos: 読んだり書いたりします.",ej:"週末は掃除したり買い物したりします。",ejr:"しゅうまつは そうじしたり かいものしたり します",ejt:"Los findes limpio, hago la compra, etc.",err:"Olvidar el する al final.",lvl:"N4"},
 {pat:"〜ながら",mean:"Mientras (a la vez)",exp:"Raíz de la forma ます + ながら: dos acciones simultáneas del mismo sujeto. 聞きながら勉強する.",ej:"テレビを見ながらご飯を食べます。",ejr:"テレビを みながら ごはんを たべます",ejt:"Como mientras veo la tele.",err:"Usarlo con sujetos distintos para cada acción.",lvl:"N4"},
 {pat:"〜まえに",mean:"Antes de ~",exp:"Verbo en forma diccionario + まえに, o sustantivo + のまえに: 寝るまえに = antes de dormir.",ej:"食べる前に手を洗います。",ejr:"たべる まえに てを あらいます",ejt:"Me lavo las manos antes de comer.",err:"Usar la forma pasada del verbo antes de まえに.",lvl:"N4"},
 {pat:"〜あとで",mean:"Después de ~",exp:"Verbo en た + あとで, o sustantivo + のあとで: 食べたあとで = después de comer.",ej:"仕事のあとで映画を見ます。",ejr:"しごとの あとで えいがを みます",ejt:"Después del trabajo veo una película.",err:"Usar la forma diccionario antes de あとで.",lvl:"N4"},
 {pat:"〜とき",mean:"Cuando ~",exp:"Frase + とき sitúa el momento: 子供のとき = cuando era niño; el tiempo del verbo (行くとき / 行ったとき) cambia el matiz.",ej:"日本へ行ったとき、写真を撮りました。",ejr:"にほんへ いったとき、しゃしんを とりました",ejt:"Cuando fui a Japón, hice fotos.",err:"Ignorar que 行くとき y 行ったとき indican momentos distintos.",lvl:"N4"},
 {pat:"〜と (natural)",mean:"Si / cuando (resultado natural)",exp:"Forma diccionario + と da una consecuencia automática: 押すと、開きます = si lo pulsas, se abre.",ej:"春になると、桜が咲きます。",ejr:"はるに なると、さくらが さきます",ejt:"Cuando llega la primavera, florecen los cerezos.",err:"Usar と con peticiones o voluntad (no se puede).",lvl:"N4"},
 {pat:"〜ば",mean:"Si ~ (condición)",exp:"Forma condicional ば plantea una condición: 安ければ買います = si es barato, lo compro.",ej:"時間があれば、行きます。",ejr:"じかんが あれば、いきます",ejt:"Si tengo tiempo, voy.",err:"Errores al formar la base ば del verbo o adjetivo.",lvl:"N4"},
 {pat:"〜たら",mean:"Si / cuando (luego)",exp:"Forma た + ら es el condicional más versátil: 雨が降ったら、行きません.",ej:"駅に着いたら、電話してください。",ejr:"えきに ついたら、でんわして ください",ejt:"Cuando llegues a la estación, llama.",err:"Olvidar que たら sirve tanto para si como para cuando.",lvl:"N4"},
 {pat:"〜なら",mean:"Si (es el caso de) ~",exp:"なら retoma un tema y da una respuesta condicional: 日本へ行くなら、京都がいいです.",ej:"安いなら、買います。",ejr:"やすいなら、かいます",ejt:"Si es barato, lo compro.",err:"Confundir なら con たら/ば; なら parte de lo que dijo el otro.",lvl:"N4"},
 {pat:"〜つもりです",mean:"Tener la intención de ~",exp:"Forma diccionario + つもりです expresa un plan firme: 行くつもりです = pienso ir.",ej:"来年、日本へ行くつもりです。",ejr:"らいねん、にほんへ いく つもりです",ejt:"El año que viene pienso ir a Japón.",err:"Usar la forma ます antes de つもり (va la forma diccionario).",lvl:"N4"},
 {pat:"〜ようと思います",mean:"Pensar hacer ~",exp:"Forma volitiva (よう/おう) + と思います: decisión reciente. 行こうと思います = creo que iré.",ej:"日本語を勉強しようと思います。",ejr:"にほんごを べんきょうしようと おもいます",ejt:"Pienso estudiar japonés.",err:"Errores al formar la base volitiva.",lvl:"N4"},
 {pat:"〜でしょう",mean:"Probablemente / supongo",exp:"でしょう (informal だろう) expresa probabilidad o pide acuerdo: 明日は雨でしょう.",ej:"明日は晴れるでしょう。",ejr:"あしたは はれるでしょう",ejt:"Mañana probablemente haga sol.",err:"Usar でしょう como futuro totalmente seguro.",lvl:"N4"},
 {pat:"〜かもしれません",mean:"Quizá / puede que ~",exp:"かもしれません expresa posibilidad, menos segura que でしょう: 雨が降るかもしれません.",ej:"彼は来ないかもしれません。",ejr:"かれは こない かもしれません",ejt:"Puede que él no venga.",err:"Confundir su grado de certeza con でしょう.",lvl:"N4"},
 {pat:"〜はずです",mean:"Se supone que / debería",exp:"はずです indica una expectativa lógica: 彼は来るはずです = se supone que vendrá.",ej:"電車は3時に着くはずです。",ejr:"でんしゃは さんじに つく はずです",ejt:"El tren debería llegar a las 3.",err:"Confundirlo con べき (deber moral).",lvl:"N4"},
 {pat:"〜んです",mean:"Es que ~ (explicación)",exp:"んです (informal んだ) da explicación o contexto: 頭が痛いんです = es que me duele la cabeza.",ej:"どうして遅れたんですか。",ejr:"どうして おくれたんですか",ejt:"¿Por qué te has retrasado?",err:"Abusar de んです en frases neutras sin matiz explicativo.",lvl:"N4"},
 {pat:"〜ても",mean:"Aunque / aun si ~",exp:"Forma て + も concede: 雨が降っても行きます = aunque llueva, voy.",ej:"高くても買います。",ejr:"たかくても かいます",ejt:"Aunque sea caro, lo compro.",err:"Confundir 〜ても con 〜てもいい (permiso).",lvl:"N4"},
 {pat:"〜のに",mean:"A pesar de que ~",exp:"のに une dos frases con un contraste inesperado y cierto reproche: 勉強したのに、落ちた.",ej:"薬を飲んだのに、まだ痛いです。",ejr:"くすりを のんだのに、まだ いたいです",ejt:"Aunque tomé la medicina, aún me duele.",err:"Confundir のに con ので (causa).",lvl:"N4"},
 {pat:"〜ので",mean:"Como / porque (educado)",exp:"ので da una razón de forma más suave y educada que から: 用事があるので、帰ります.",ej:"熱があるので、休みます。",ejr:"ねつが あるので、やすみます",ejt:"Como tengo fiebre, descanso.",err:"Tras adjetivos な o sustantivos va なので, no ので.",lvl:"N4"},
 {pat:"〜ことができる",mean:"Poder / ser capaz de ~",exp:"Forma diccionario + ことができる expresa capacidad: 泳ぐことができます = sé nadar.",ej:"日本語を話すことができます。",ejr:"にほんごを はなす ことが できます",ejt:"Sé hablar japonés.",err:"Mezclarlo con la forma potencial sin coherencia.",lvl:"N4"},
 {pat:"〜られる (potencial)",mean:"Forma potencial (poder hacer)",exp:"Potencial: 食べる→食べられる, 飲む→飲める, する→できる. Lo que se puede hacer suele ir con が.",ej:"漢字が読めます。",ejr:"かんじが よめます",ejt:"Puedo leer kanji.",err:"Usar を en vez de が con el potencial.",lvl:"N4"},
 {pat:"〜よう (volitivo)",mean:"Vamos / voy a (informal)",exp:"Volitiva informal (行こう, 食べよう, しよう): propone o decide, versión coloquial de ましょう.",ej:"一緒に帰ろう。",ejr:"いっしょに かえろう",ejt:"Volvamos juntos.",err:"Errores al formar la volitiva según el grupo del verbo.",lvl:"N4"},
 {pat:"〜られる (pasiva)",mean:"Voz pasiva",exp:"La pasiva (見られる, 言われる, される): el sujeto recibe la acción. 先生にしかられた = me regañó el profesor.",ej:"みんなに笑われました。",ejr:"みんなに わらわれました",ejt:"Todos se rieron de mí.",err:"Confundir la pasiva con el potencial (igual forma en ru-verbos).",lvl:"N4"},
 {pat:"〜てみる",mean:"Probar a hacer ~",exp:"Forma て + みる: hacer algo para ver qué tal. 食べてみる = probar a comer.",ej:"この服を着てみます。",ejr:"この ふくを きてみます",ejt:"Me pruebo esta ropa.",err:"Tomarlo literalmente como ver.",lvl:"N4"},
 {pat:"〜ておく",mean:"Hacer algo de antemano",exp:"Forma て + おく: preparar con antelación. 予約しておく = reservar. Coloquial: 〜とく.",ej:"飲み物を買っておきます。",ejr:"のみものを かっておきます",ejt:"Compro las bebidas de antemano.",err:"Ignorar el matiz de preparación.",lvl:"N4"},
 {pat:"〜てしまう",mean:"Acabar haciendo / sin querer",exp:"Forma て + しまう: completar algo o hacerlo sin querer (con pena). Coloquial: 〜ちゃう.",ej:"宿題を忘れてしまいました。",ejr:"しゅくだいを わすれて しまいました",ejt:"Se me olvidaron los deberes.",err:"Pasar por alto el matiz de arrepentimiento.",lvl:"N4"},
 {pat:"〜そうです (apariencia)",mean:"Parece que ~ (por lo que veo)",exp:"Raíz de adjetivo/verbo + そうです: impresión visual. おいしそうです = tiene buena pinta.",ej:"雨が降りそうです。",ejr:"あめが ふりそうです",ejt:"Parece que va a llover.",err:"Confundirlo con そうです de rumor.",lvl:"N4"},
 {pat:"〜そうです (rumor)",mean:"Dicen que ~ (información oída)",exp:"Forma normal + そうです transmite algo que oíste: 雨が降るそうです = dicen que va a llover.",ej:"彼は来ないそうです。",ejr:"かれは こない そうです",ejt:"Dicen que él no viene.",err:"Mezclarlo con そうです de apariencia (distinta base).",lvl:"N4"},
 {pat:"〜ようです",mean:"Parece que ~ (deducción)",exp:"ようです expresa una conjetura basada en indicios: 誰かいるようです = parece que hay alguien.",ej:"風邪をひいたようです。",ejr:"かぜを ひいた ようです",ejt:"Parece que me he resfriado.",err:"Confundir el grado de certeza con そう / らしい.",lvl:"N4"},
 {pat:"あげる・くれる・もらう",mean:"Dar y recibir",exp:"あげる (yo doy a otro), くれる (otro me da a mí), もらう (yo recibo). El punto de vista cambia el verbo.",ej:"友だちにプレゼントをあげました。",ejr:"ともだちに プレゼントを あげました",ejt:"Le di un regalo a un amigo.",err:"Usar あげる cuando alguien te da algo (es くれる).",lvl:"N4"},
 {pat:"〜てくれる・てもらう",mean:"Hacer favores",exp:"Forma て + あげる/くれる/もらう: hacer algo por alguien. 手伝ってくれた = me ayudó.",ej:"友だちが手伝ってくれました。",ejr:"ともだちが てつだって くれました",ejt:"Un amigo me ayudó.",err:"Equivocar la dirección del favor (くれる vs あげる).",lvl:"N4"},
 {pat:"〜すぎる",mean:"Demasiado ~",exp:"Raíz de verbo/adjetivo + すぎる: exceso. 食べすぎる = comer demasiado; 高すぎる = demasiado caro.",ej:"昨日は食べすぎました。",ejr:"きのうは たべすぎました",ejt:"Ayer comí demasiado.",err:"Olvidar quitar い/な del adjetivo antes de すぎる.",lvl:"N4"},
 {pat:"〜やすい・〜にくい",mean:"Fácil / difícil de ~",exp:"Raíz de la forma ます + やすい (fácil) o にくい (difícil): 読みやすい = fácil de leer.",ej:"このペンは書きやすいです。",ejr:"この ペンは かきやすいです",ejt:"Este boli es fácil de usar.",err:"Conjugarlos como verbos en vez de como adjetivos い.",lvl:"N4"},
 {pat:"〜かた",mean:"Manera de hacer ~",exp:"Raíz de la forma ます + 方(かた): forma de hacer algo. 使い方 = modo de uso; 作り方 = receta.",ej:"漢字の書き方を教えてください。",ejr:"かんじの かきかたを おしえて ください",ejt:"Enséñame a escribir kanji.",err:"Olvidar que el objeto pasa a llevar の (本の読み方).",lvl:"N4"},
 {pat:"〜し",mean:"Y además (razones)",exp:"し enumera razones o cualidades que se suman: 安いし、おいしいし、よく行きます.",ej:"この店は安いし、近いです。",ejr:"この みせは やすいし、ちかいです",ejt:"Esta tienda es barata y, además, está cerca.",err:"Usar し donde solo hay un motivo (mejor から).",lvl:"N4"}
]

};
